<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
use Magento\Framework\App\Action\Action;

// @codingStandardsIgnoreFile

?>
<?php
/**
 * Product list template
 *
 * @var $block \Magento\Catalog\Block\Product\ListProduct
 */
?>
<?php
$_productCollection = $block->getLoadedProductCollection();
$_helper = $this->helper('Magento\Catalog\Helper\Output');
?>
<?php if (!$_productCollection->count()): ?>
    <div class="message info empty"><div><?= /* @escapeNotVerified */ __('We can\'t find products matching the selection.') ?></div></div>
<?php else: ?>
    <?= $block->getToolbarHtml() ?>
    <?= $block->getAdditionalHtml() ?>
    <?php
    if ($block->getMode() == 'grid') {
        $viewMode = 'grid';
        $image = 'category_page_grid';
        $showDescription = false;
        $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
    } else {
        $viewMode = 'list';
        $image = 'category_page_list';
        $showDescription = true;
        $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::FULL_VIEW;
    }
    /**
     * Position for actions regarding image size changing in vde if needed
     */
    $pos = $block->getPositioned();
    ?>
    <div class="products wrapper <?= /* @escapeNotVerified */ $viewMode ?> products-<?= /* @escapeNotVerified */ $viewMode ?>">
        <?php $iterator = 1; ?>
        <ol class="products list items product-items">
            <?php /** @var $_product \Magento\Catalog\Model\Product */ ?>
            <?php foreach ($_productCollection as $_product): ?>
                <?= /* @escapeNotVerified */ ($iterator++ == 1) ? '<li class="item product product-item">' : '</li><li class="item product product-item">' ?>
                <div class="product-item-info" data-container="product-grid">

                    <?php
                    /*
                     $magazine_images=$_product->getMagazineImages();
                    if($magazine_images!='')
                    {
                        $helper=$this->helper('Homescapes\MagazineImages\Helper\Data');
                        $imagePath =$helper->getMagazinImage($magazine_images);?>
                        <?php 
                        if($imagePath!='')
                        { ?>
                            <div class="product-list-magazine-images">
                            <img src="<?php echo $imagePath ?>" alt="<?php echo $_product->getName(); ?>" >
                            </div>
                        <?php
                        }
                    } */


                        $festive_images=$_product->getFestiveImages();

                        if($festive_images!='')
                        {
                            $helper=$this->helper('Homescapes\MagazineImages\Helper\Data');
                            $imagePath =$helper->getMagazinImage($festive_images);?>
                            <?php 
                            if($imagePath!='')
                            { ?>
                                <div class="festive-image-label">
                                <img src="<?php echo $imagePath ?>" alt="<?php echo $_product->getName(); ?>" >
                                </div>
                            <?php
                            }
                        }

                     ?>

                    <?php
                    if ($_product->isAvailable()){
                     $newLabel = $this->helper('Homescapes\General\Helper\Data')->isNew($_product);
                        if($newLabel){?>                
                        <div class="product-label">
                            <span class="new"><?php echo __('New') ?></span>
                        </div>
                        <?php }  ?>
                    <?php }  ?>
                    <?php if ($_product->isAvailable()): ?>    
                    <?php 
                    
                        // Product Image Label Sale
                        if($_product->getProductLabelSale()){?>  
                        <?php echo "FR" ?>              
                        <div class="product-label">
                            <span class="sale-label"><?php echo __($_product->getProductLabelSale()) ?></span>
                        </div>
                        <?php }  ?>
                    <?php endif; ?>
                    <?php       //Delivery for Christmas
                        if($_product->getInTimeXmas()){?>                
                        <div class="product-christmas-label">
                            <span class="christmas-label"><?php echo __($_product->getInTimeXmas()) ?></span>
                        </div>
                        <?php }  ?>  
                    <?php
                    $productImage = $block->getImage($_product, $image);
                    if ($pos != null) {
                        $position = ' style="left:' . $productImage->getWidth() . 'px;'
                            . 'top:' . $productImage->getHeight() . 'px;"';
                    }
                    ?>
                    <?php // Product Image ?>
                    <a href="<?= /* @escapeNotVerified */ $_product->getProductUrl() ?>" class="product photo product-item-photo" tabindex="-1">
                        <?= $productImage->toHtml() ?>
                    </a>
                    <?php
                        $_helperGallery = $this->helper('Homescapes\General\Helper\Image')->getHoverImage($_product);
                       
                     ?>
                    <?php if($_helperGallery){ ?> 
                    <a href="<?= /* @escapeNotVerified */ $_product->getProductUrl() ?>" class="product photo product-item-photo hover" tabindex="-1">
                        <img src="<?php echo $_helperGallery; ?>" /> 
                    </a>
                    <?php } ?>
                    
                    <div class="product details product-item-details">
                        <?php
                            $_productNameStripped = $block->stripTags($_product->getName(), null, true);
                        ?>
                        <strong class="product name product-item-name">
                            <a class="product-item-link"
                               href="<?= /* @escapeNotVerified */ $_product->getProductUrl() ?>">
                                <?= /* @escapeNotVerified */ $_helper->productAttribute($_product, $_product->getName(), 'name') ?>
                            </a>
                        </strong>
                            <?php if ($_product->isAvailable()): ?>
                                  <?php //In Stock ?>  
                                <?php else: ?>
                                    <div class="stock unavailable"><span><?= /* @escapeNotVerified */ __('Out of stock') ?></span></div>
                            <?php endif; ?>

                        <?php 
                        $helper = $this->helper('Homescapes\General\Helper\Data');
                                
                            if($_product->getTypeId() == "configurable" || $_product->getTypeId() == "grouped"){
                                echo $helper->getpriceRange($_product);
                            }else{
                                echo $block->getProductPrice($_product);
                            }
                        ?>                       
                        <?= $block->getProductDetailsHtml($_product) ?>
                        <?= $block->getReviewsSummaryHtml($_product, $templateType) ?>
                        
                    </div>
                </div>
                <?= ($iterator == count($_productCollection)+1) ? '</li>' : '' ?>
            <?php endforeach; ?>
        </ol>
    </div>
    <?= $block->getToolbarHtml() ?>
    <?php /*<div data-mage-init='{"orderswatches":{"urlgetproducts": "<?php echo $block->getUrl('orderswatches/ajax/fetchProducts') ?>",
         "urlHeaderSwatch": "<?php echo $block->getUrl('orderswatches/ajax/headerSwatch') ?>",
         "removeProductSample": "<?php echo $block->getUrl('orderswatches/ajax/removeProductSample') ?>",
         "closeswatch": "<?php echo $block->getUrl('orderswatches/ajax/setswatch') ?>"}}' class="container-wrapper" ></div> */ ?>
    <?php if (!$block->isRedirectToCartEnabled()) : ?>
        <script type="text/x-magento-init">
        {
            "[data-role=tocart-form], .form.map.checkout": {
                "catalogAddToCart": {
                    "product_sku": "<?= /* @NoEscape */ $_product->getSku() ?>"
                }
            }
        }
        </script>
    <?php endif; ?>
<?php endif; ?>