<?php

/**
 * @var $block \MagicToolbox\MagicScroll\Block\Html\Head
 */

if (!$block->isVisibile()) {
    return;
}

$jsUrl = $block->getViewFileUrl('MagicToolbox_MagicScroll::js/magicscroll.js');
$jsPath = dirname($jsUrl);
$cssUrl = $block->getViewFileUrl('MagicToolbox_MagicScroll::css/magicscroll.css');
$cssPath = dirname($cssUrl);

$tool = $block->magicToolboxHelper->getToolObj();
$tool->params->resetProfile();

$headers = $tool->getHeadersTemplate($jsPath, $cssPath);

//NOTE: fix to support 'Minify JavaScript/CSS Files' options
if (preg_match('#\.min\.css$#', $cssUrl)) {
    $headers = preg_replace('#\.css\b#', '.min.css', $headers);
}
if (preg_match('#\.min\.js$#', $jsUrl)) {
    $headers = preg_replace('#\.js\b#', '.min.js', $headers);
}

echo $headers;
