<?php /** @var \JustShout\Gfs\Block\Html\Head $block */ ?>

<!-- GFS HEAD START -->
<script src="<?= $block->getViewFileUrl('JustShout_Gfs::gfs-checkout/webcomponentsjs/webcomponents-lite.js') ?>"></script>
<link rel="import" href="<?= $block->getViewFileUrl('JustShout_Gfs::gfs-checkout/gfs-checkout-widget/gfs-checkout-widget.html') ?>">
<link rel="import" href="<?= $block->getViewFileUrl('JustShout_Gfs::gfs-checkout/gfs-delivery-address/gfs-delivery-address.html') ?>">

<script>
    var gfsData = {
        'accessToken': '<?= $block->getAccessToken() ?>',
        'currency_symbol': '<?= $block->getCurrencySymbol() ?>',
        'delivery_types': '<?= $block->getDeliveryTypes() ?>',
        'standard_delivery_title': '<?= $block->getStandardDeliveryTitle() ?>',
        'calendar_delivery_title': '<?= $block->getCalendarDeliveryTitle() ?>',
        'drop_point_title': '<?= $block->getDropPointTitle() ?>',
        'service_sort_order': '<?= $block->getServiceSortOrder() ?>',
        'home_icon': '<?= $block->getMapHomeIcon() ?>',
        'use_standard': '<?= $block->getUseStandard() ?>',
        'use_calendar': '<?= $block->getUseCalendar() ?>',
        'use_drop_points': '<?= $block->getUseDropPoints() ?>',
        'default_service': '<?= $block->getDefaultService() ?>',
        'default_carrier': '<?= $block->getDefaultCarrier() ?>',
        'default_carrier_code': '<?= $block->getDefaultCarrierCode() ?>',
        'default_price': '<?= $block->getDefaultPrice() ?>',
        'default_min_delivery_time': '<?= $block->getDefaultMinDeliveryTime() ?>',
        'default_max_delivery_time': '<?= $block->getDefaultMaxDeliveryTime() ?>'
    };
    var gfsLogoSrc = '<?= $block->getGfsLogoSrc() ?>';
</script>

<script id="gfs-checkout-widget-template" type="text/x-magento-template">
    <gfs-checkout
            access-token="<%- data.access_token %>"
            sessionid="sessionID"
            checkout-results="checkoutResult"
            checkout-data="checkoutData"
            gfs-data="<%- data.gfs_data %>"
            initial-address="<%- data.initial_address %>"
            currency-symbol="<%- data.currency_symbol %>"
            delivery-types="<%- data.delivery_types %>"
            standard-delivery-title="<%- data.standard_delivery_title %>"
            calendar-delivery-title="<%- data.calendar_delivery_title %>"
            drop-point-title="<%- data.drop_point_title %>"
            service-sort-order="<%- data.service_sort_order %>"
            <?php if ($block->getMapHomeIcon()): ?>home-icon="<%- data.home_icon %>"<?php endif; ?>
            use-standard="<%- data.use_standard %>"
            use-calendar="<%- data.use_calendar %>"
            use-drop-points="<%- data.use_drop_points %>"
            <?php if ($block->getUseStores()): ?>use-stores<?php endif; ?>
            <?php if ($block->getUseDropPointStores()): ?>use-droppoints-stores<?php endif; ?>
            default-service="<%- data.default_service %>"
            default-carrier="<%- data.default_carrier %>"
            default-carrier-code="<%- data.default_carrier_code %>"
            default-price="<%- data.default_price %>"
            default-min-delivery-time="<%- data.default_min_delivery_time %>"
            default-max-delivery-time="<%- data.default_max_delivery_time %>">
    </gfs-checkout>
</script>

<script id="gfs-delivery-address-template" type="text/x-magento-template">
    <gfs-delivery-address
            default-street-address="<%- data.address %>">
    </gfs-delivery-address>
</script>

<script>
    require([
        'moment'
    ], function(moment) {
        window.moment = moment;
        return moment;
    });
</script>

<style type="text/css">
    #widgetContainer .header {
        background: <?= $block->getColorPrimary() ?>;
    }

    #widgetContainer .header h3,
    #widgetContainer .header label {
        color: <?= $block->getColorSecondary() ?>;
    }

    #widgetContainer span.price {
        color: <?= $block->getColorTertiary() ?>;
    }
</style>
<!-- GFS HEAD END -->

