<?php
/**
 * @author Amasty Team
 * @copyright Copyright (c) 2021 Amasty (https://www.amasty.com)
 * @package Amasty_GroupedOptions
 */
?>
<?php /** @var \Amasty\GroupedOptions\Block\Adminhtml\Group\Edit\After $block */?>
<script>
    require([
        'Amasty_GroupedOptions/js/group-visual'
    ], function(Visual) {
        Visual(<?= /* @noEscape */ $block->getJsonVisualConfig() ?>);
    });
</script>
