<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/** @var $block \Magento\ProductAlert\Block\Email\Stock */
?>
<?php if ($_products = $block->getProducts()) : ?>
    <p><?= $block->escapeHtml(__('Back in stock alert!')) ?></p><br>


<p><?= $block->escapeHtml(__('We wanted to let you know that this product is now available.')) ?></p>
    <table>
    <?php foreach ($_products as $_product) : ?>
        <tr>
            <td class="col photo">
                <a href="<?= $block->escapeUrl($_product->getProductUrl()) ?>" title="<?= $block->escapeHtmlAttr($_product->getName()) ?>" class="product photo">
                    <?= $block->getImage($_product, 'product_thumbnail_image', ['class' => 'photo image'])->toHtml() ?>
                </a>
            </td>
            <td class="col item">
                <p>
                    <strong class="product name">
                        <a href="<?= $block->escapeUrl($_product->getProductUrl()) ?>"><?= $block->escapeHtml($_product->getName()) ?></a>
                    </strong>
                </p>
                <?php if ($shortDescription = $block->getFilteredContent($_product->getShortDescription())) : ?>
                    <p><small><?= /* @noEscape */  $shortDescription ?></small></p>
                <?php endif; ?>
                <?=
                $block->getProductPriceHtml(
                    $_product,
                    \Magento\Catalog\Pricing\Price\FinalPrice::PRICE_CODE,
                    \Magento\Framework\Pricing\Render::ZONE_EMAIL,
                    [
                        'display_label' => __('Price:')
                    ]
                );
                ?>
            
            </td>
        </tr>
    <?php endforeach; ?>
    </table>
    <p><a href="<?= $block->escapeUrl($block->getUnsubscribeUrl()) ?>"><?= $block->escapeHtml(__('Unsubscribe from all stock alerts')) ?></a></p>
<?php endif; ?>
