<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/** @var $block \Magento\Catalog\Block\Product\View */
?>
<?php $_product = $block->getProduct(); ?>
<?php $buttonTitle = __('Add to Cart'); ?>
<?php if ($_product->isSaleable()): ?>
<?php if($this->helper('Homescapes\Preorder\Helper\Data')->isPreOrder($_product)){  ?>
<span class="preoder"><i class="fas fa-truck"></i> <?php echo $_product->getPreOrderNote(); ?></span>
<?php } ?>
<div class="box-tocart">
    <div class="fieldset">
        <?php if ($block->shouldRenderQuantity()): ?>
        <div class="field qty">
            <label class="label" for="qty"><span><?= /* @escapeNotVerified */ __('Qty') ?></span></label>
            <div class="control" data-mage-init='{
                                        "qtyInput":{"qtyInputSelector": "#qty-<?php /* @escapeNotVerified */ echo $_product->getId() ?>",
                                        "qtyIncrementSelector":"#inc-qty-<?php /* @escapeNotVerified */ echo $_product->getId() ?>",
                                        "qtyDecrementSelector":"#dec-qty-<?php /* @escapeNotVerified */ echo $_product->getId() ?>"
                                        }
                                    }'>
                <div class="decreaseQty" id="dec-qty-<?php /* @escapeNotVerified */ echo $_product->getId() ?>" >-</div>
                <input type="number"
                       name="qty"
                       id="qty-<?php /* @escapeNotVerified */ echo $_product->getId() ?>"
                       value="<?= /* @escapeNotVerified */ $block->getProductDefaultQty() * 1 ?>"
                       title="<?= /* @escapeNotVerified */ __('Qty') ?>"
                       class="input-text qty"
                       data-validate="<?= $block->escapeHtml(json_encode($block->getQuantityValidators())) ?>"
                       data-default-qty="<?= /* @escapeNotVerified */ $block->getProductDefaultQty() * 1 ?>"
                       />
                <div class="increaseQty" id="inc-qty-<?php /* @escapeNotVerified */ echo $_product->getId() ?>">+</div>
            </div>
        </div>
        <?php endif; ?>
        <div class="actions">
            <button type="submit"
                    title="<?= /* @escapeNotVerified */ $buttonTitle ?>"
                    class="action primary tocart"
                    id="product-addtocart-button">
                <span><?= /* @escapeNotVerified */ $buttonTitle ?></span>
            </button>
            <?= $block->getChildHtml('', true) ?>
        </div>
        <div class="mg-ajaxcart-dialog" id="ajaxcart-dialog-<?php echo $_product->getId() ?>">
            <div class="main-panel">
                    <div class="product-info">
                            <span class="msg"><?php echo __('Added to your basket');?><br>
                            <div class="name"></div></span>
                    </div>
                    <div class="button-set">
                            <a href="<?php echo $block->getUrl('checkout/cart'); ?>" class="button goto-cart cart-button"><?php echo __('View cart');?></a>                            
                    </div>
                    <div style="clear:both;"></div>
            </div>
        </div>
    </div>
</div>
<?php endif; ?>
<?php if ($block->isRedirectToCartEnabled()) : ?>
<script type="text/x-magento-init">
    {
        "#product_addtocart_form": {
            "Magento_Catalog/product/view/validation": {
                "radioCheckboxClosest": ".nested"
            }
        }
    }
</script>
<?php else : ?>
<script type="text/x-magento-init">
    {
        "#product_addtocart_form": {
            "Magento_Catalog/js/validate-product": {}
        }
    }
</script>
<?php endif; ?>
<style>
    
    .mg-ajaxcart-dialog{
            background: #fff;
    border-radius: 2px;
    margin-bottom: 10px;
    border: #005dbd solid 1px;
    padding: 0;
    width: 100%;
    position: relative;
    clear: both;
    }
    .mg-ajaxcart-dialog .product-info {
        padding: 12px 20px 12px 20px;
        text-align: left;
    }

    .mg-ajaxcart-dialog .button-set {
        background: #f7f7f7;
        float: left;
        width: 100%;
        padding: 12px 20px;
        margin: 9px 0 0 0;
    }
    
    .mg-ajaxcart-dialog .button-set a.goto-cart.cart-button {
        float: left;
        color: #fff;
        font-size: 15px;
        font-weight: bold;
        padding: 5px 15px;
        margin: 3px 20px 0 0;
        background: #005dbd;
    }
</style>