<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php if ($detailedInfoGroup = $block->getGroupChildNames('detailed_info', 'getChildHtml')):?>
    <div class="product info detailed">
        <?php $layout = $block->getLayout(); ?>
		
        <div id="element" data-mage-init='{"accordion":{"openedState": "active", "collapsible": true, "active": [0], "multipleCollapsible": true}}'>	
			
            <?php foreach ($detailedInfoGroup as $name):?>
                <?php
                    $html = $layout->renderElement($name);
                    if (!trim($html)) {
                        continue;
                    }
                    $alias = $layout->getElementAlias($name);
                    $label = $block->getChildData($alias, 'title');
                ?>
			
			<a class="data switch"
                       tabindex="-1"
                       data-toggle="switch"
                       href="#<?= /* @escapeNotVerified */ $alias ?>"
                       id="tab-label-<?= /* @escapeNotVerified */ $alias ?>-title">
                <div class="data item title card-header"
                     aria-labeledby="tab-label-<?= /* @escapeNotVerified */ $alias ?>-title"
                     data-role="collapsible" id="tab-label-<?= /* @escapeNotVerified */ $alias ?>">
					
					
                    
                        <?= /* @escapeNotVerified */ $label ?>
                   
					
					
                </div>
			
			 </a>
                <div class="card-body content" id="<?= /* @escapeNotVerified */ $alias ?>" data-role="content">
                    <?= /* @escapeNotVerified */ $html ?>
                </div>
			
			
            <?php endforeach;?>
        </div>

    </div>

<script>

require([
    'jquery',
    'accordion'
], function ($) {
    'use strict';

    jQuery( document ).ready(function() {                      
        jQuery( "#narrow-by-list" ).accordion({
            "openedState": "active",
            "collapsible": true,
            "active": [0], /** Integrat Dynamic open tab  */
            "multipleCollapsible": true,
        });
    });                 
});

</script>

<?php endif; ?>
