<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php /* @var $block \Magento\Catalog\Block\Product\View\AbstractView */?>
<?php $_product = $block->getProduct() ?>

<?php if ($block->displayProductStockStatus()): ?>

	
    <?php if ($_product->isAvailable()): ?>
        <div class="stock" title="<?= /* @escapeNotVerified */ __('Availability') ?>">
			<span class="stock-label"><?= /* @escapeNotVerified */ __('Availability')  ?>: </span>
            <span class="available"> <?= /* @escapeNotVerified */ __('In stock') ?></span>
        </div>
    <?php else: ?>
        <div class="stock" title="<?= /* @escapeNotVerified */ __('Availability') ?>">
			<span class="stock-label"><?= /* @escapeNotVerified */ __('Availability')  ?>: </span>
            <span class="unavailable"> <?= /* @escapeNotVerified */ __('Out of stock') ?></span>
        </div>
    <?php endif; ?>
<?php endif; ?>
