
<!-- Google Tag Manager-->
<noscript><iframe src="//www.googletagmanager.com/ns.html?id=GTM-MVZ5CB"
height="0" width="0" style="display:none;visibility:hidden"></iframe></noscript>
<script>(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
'//www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);
})(window,document,'script','dataLayer','GTM-MVZ5CB');</script>
<!-- End Google Tag Manager -->

<script>
  require([
        'jquery'
    ], function ($) {
    		setTimeout(function(){ 
    			var $containerWidth = $(window).width();
				console.log('hide element 123');
				//$('.mobile-bar .action.search').css("display","inline-block");
				$('.mobile-bar .action.search').removeAttr("style");
    		 }, 7000)
			  
    });
</script>
