
<meta name="msvalidate.01" content="C63261BA861CE8AAA32C2E218D9183FA" />
<!-- Facebook Pixel Code -->


<script>
<!-- Facebook Pixel Code -->
! function (f, b, e, v, n, t, s) {
        if (f.fbq) return;
        n = f.fbq = function () {
            n.callMethod ?
                n.callMethod.apply(n, arguments) : n.queue.push(arguments);
        };
        if (!f._fbq) f._fbq = n;
        n.push = n;
        n.loaded = !0;
        n.version = '2.0';
        n.queue = [];
        t = b.createElement(e);
        t.async = !0;
        t.src = v;
        s = b.getElementsByTagName(e)[0];
        s.parentNode.insertBefore(t, s);
    }
    (window, document, 'script', '//connect.facebook.net/en_US/fbevents.js');
    // Custom Audience Pixel ID.
    fbq('init', '225375511131707');
    fbq('track', "PageView");

</script>
<noscript><img height="1" width="1" style="display:none"
src="https://www.facebook.com/tr?id=225375511131707&ev=PageView&noscript=1"
/></noscript>

<!-- End Facebook Pixel Code -->
<!-- Below code for bing -->
<script type="text/javascript">
(function(w,d,t,r,u){var f,n,i;w[u]=w[u]||[],f=function(){var o={ti:"4055406"};o.q=w[u],w[u]=new UET(o),w[u].push("pageLoad")},n=d.createElement(t),n.src=r,n.async=1,n.onload=n.onreadystatechange=function(){var s=this.readyState;s&&s!=="loaded"&&s!=="complete"||(f(),n.onload=n.onreadystatechange=null)},i=d.getElementsByTagName(t)[0],i.parentNode.insertBefore(n,i)})(window,document,"script","//bat.bing.com/bat.js","uetq");
</script>

<noscript>
    <img src="//bat.bing.com/action/0?ti=4055406&Ver=2" height="0" width="0" style="display:none; visibility: hidden;" />
</noscript>
<!-- end -->