

<meta property="og:type" content="website"/>
<meta property="og:title" content="Homescapes - Bed &amp; Bath Linen, Cushions, Curtains, Furniture"/>
<meta property="og:description" content="Homescapes manufactures and sells top quality bed linen, bath linen, kitchen linens with a large selection of hardwood furniture and an amazing range of soft furnishings."/>
<meta property="og:url" content="<?php echo $block->getUrl('contact'); ?>"/>
<meta property="og:site_name" content="Homescapes"/>
<meta property="og:image" content="https://smhttp-ssl-82676-media.nexcesscdn.net/pub/media/og_image/default/homescapes_fullsize.jpg"/>
<meta property="og:image:width" content="512"/>
<meta property="og:image:height" content="512"/>
<meta property="twitter:card" content="summary_large_image"/>
<meta property="twitter:site" content="HomescapesUK"/>
<meta property="twitter:title" content="Homescapes - Bed &amp; Bath Linen, Cushions, Curtains, Furniture"/>
<meta property="twitter:description" content="Homescapes manufactures and sells top quality bed linen, bath linen, kitchen linens with a large selection of hardwood furniture and an amazing range of soft furnishings."/>