<?php $_items = $block->getReviewsCollection()->getItems();
$_product = $block->getProduct();
$helper = $this->helper('Homescapes\Ratings\Helper\Data');


$average_ratings_count = array(1=>0,2=>0,3=>0,4=>0,5=>0);
$votes = array();
$review = array();
$rating_code = array('price'=>0,'quality'=>0,'value'=>0);

$based_recommendation = 0;
foreach ($_items as $rating_review){

	$review_votes = $rating_review->getRatingVotes(); 

                 $rdata = $review_votes->getData();
                  
                 if($helper->getRecommend($rating_review->getReviewId())==1){
                     $based_recommendation= ++$based_recommendation;
                 }

                 $cnt = count($rdata);
                 for($i=0;$i<$cnt;$i++){
                    if($rdata[$i]['rating_code'] == 'Price'){
                        $rating_code['price']=$rating_code['price']+$rdata[$i]['percent'];
                    }elseif($rdata[$i]['rating_code'] == 'Value'){
                        $rating_code['value']=$rating_code['value']+$rdata[$i]['percent'];
                    }elseif($rdata[$i]['rating_code'] == 'Quality'){
                        $rating_code['quality']=$rating_code['quality']+$rdata[$i]['percent'];
                    }
                    
                 }
                
                $average_ratings = ($rdata[0]['percent']+$rdata[1]['percent']+$rdata[2]['percent'])/3;               
                if($average_ratings >0 && $average_ratings<=39){
                    $average_ratings_count[1]=++$average_ratings_count[1];
                }elseif($average_ratings >=40 && $average_ratings<=59){
                    $average_ratings_count[2]=++$average_ratings_count[2];
                }elseif($average_ratings >=60 && $average_ratings<=79){
                    $average_ratings_count[3]=++$average_ratings_count[3];
                }elseif($average_ratings >=80 && $average_ratings<=99){
                    $average_ratings_count[4]=++$average_ratings_count[4];
                }else{
                     $average_ratings_count[5]=++$average_ratings_count[5];
                }
}

  krsort($average_ratings_count);
 
?>

<div class="box-collateral box-reviews" id="customer-reviews">
    <?php if (count($_items)):$totalreivew = count($_items);?>
        <div class="rating-review">
        <h3><?php echo __('Rating & Reviews') ?></h3>
        <div class="rating-section">
            <ul>
                <li class="average-ratings">
                    <div class="dyn-rating">	
						<label><?php echo __('Overall') ?></label>
						<div class="ratings">
							<div class="rating-box">
								<div class="rating" style="width:<?php echo round($_product->getRatingSummary()->getRatingSummary()) ?>%;"></div>
							</div>
                        </div>
                        <p><?php echo round(($_product->getRatingSummary()->getRatingSummary())/20, 1) ?></p>
                        <span><?php echo __('Out of 5') ?></span>
                    </div>
                   
                    <span><?php echo __('Based on '.$totalreivew.' ratings') ?></span>
                    <div class="overall-ratings">
					<ul>
                   <?php  foreach($rating_code as $label => $sumofratings){?>
                        <li>
                            <span class="title"><?php echo __($label); ?></span>
                            <div class="filter-box">
                                <div class="filter" style="width: <?php echo round($sumofratings/$totalreivew,2); ?>%;"></div>
                            </div>                            
                        </li> 
                    <?php }?>
						
                    </ul>
                   
                    </div>
                </li>
                
                <li class="filter-review">
                    <p class="title"><?php echo __('Select a row below to filter reviews.') ?></p>
                    <ul>
                    <?php foreach($average_ratings_count as $key => $val){?>
                        <li data-star="<?php echo $key?>" class="star_ratings">
                            <span class="count"><?php echo $key?></span>
                            <div class="filter-box">
                            <?php $star_rating = ($val*100)/$totalreivew;?>
                                <div class="filter" style="width: <?php echo round($star_rating,2); ?>%;"></div>
                            </div>
                            <span class="value" id="value_<?php echo $key;?>"><?php echo $val?></span>
                        </li> 
                    <?php }?>  
                                            
                    </ul>
                </li>
                
                <li class="recommends-items">
                    <div class="dyn-rating">
                    <?php $br = ($based_recommendation*100)/$totalreivew;?>
                        <p><?php echo round($br, 2)."%"?></p>
                        <span><?php echo __('recommend') ?></span>
                    </div>
                    <p><?php echo __('Based on '.$totalreivew.' recommendations') ?></p>
                    <span><?php echo __('Would you recommend this item?') ?></span>
                    <div class="action">
                        <a class="yes fancybox review-popup" href="#inline1"><?php echo __('Yes')?></a>
                        <a class="No fancybox review-popup" href="#inline1" ><?php echo __('No')?></a>
                    </div>
                </li>
                
                <li class="write-review">
                    <div class="img-box">
			<?php
				$imageType = 'product_thumbnail_image';
				$image = $block->getImage($_product, $imageType); 
			?>
	   <img src="<?php echo $image->getImageUrl(); ?>" alt="test"/>                       
                    </div>
                    <p><?php echo __('Have you purchased this item?') ?></p>
                    <a href="#inline1" class="write-review fancybox review-popup"><?php echo __('write a review') ?></a>
                </li>
            </ul>
        </div>
    </div>
        <div class="review-heading">
            <h2>
                <?php echo __('Customer Reviews') ?>
                <span id="review_count">[<?php echo count($_items); ?>]</span>
            </h2>

            <div class="review_filter">
				<div data-star="all" class="star_ratings star-value"> 
					<span class="value_filter" ></span>
				</div>
				<div data-star="all" class="star_ratings clear-all"> <?php echo __('Clear all') ?>
					<span class="icon"></span>
					<span class="value" id="value_all"><?php echo $totalreivew ?></span>
				</div>
			</div>		
        </div>
        <dl id="dl_review">
        <?php $it=0;foreach ($_items as $_review):$it++;?>
        <?php 
                $_votes = $_review->getRatingVotes(); 
                $rowdata = $_votes->getData();               
                $average_ratings = ($rowdata[0]['percent']+$rowdata[1]['percent']+$rowdata[2]['percent'])/3;               
                ?> 
            <dt data-rating="<?php echo round($average_ratings/20)?>" <?php if($it >4){?>class="inactive"<?php }?>>
				              
				<?php if (count($_votes)): ?>
                <table class="ratings-table">
                    <colgroup>
                        <col class="review-label" />
                        <col class="review-value" />
                    </colgroup>
                    <tbody>                    
						<tr>
                           
                            <td colspan="2">
                                <div class="rating-box">
									<div class="rating" style="width:<?php echo $average_ratings ?>%;"></div>
								</div>
                            </td>
                        </tr>
						<tr>
                            
                            <td colspan="2">
                                <span class="review-meta">
									<?php echo __('Review by '.($_review->getNickname())) ?>
									<br> 
								   <label><?php echo __('Posted on '.date('d/m/Y', strtotime($_review->getCreatedAt()))); ?></label>
								</span>
								
                            </td>
                        </tr>
                        <?php foreach ($_votes as $_vote): ?>
                        <tr>
                            <th><?php echo ($_vote->getRatingCode()) ?></th>
                            <td>
                                <div class="rating-box">
                                    <div class="rating" style="width:<?php echo $_vote->getPercent() ?>%;"></div>
                                </div>
                            </td>
                        </tr>
                        <?php endforeach; ?>
                    </tbody>
                </table>
                <?php endif; ?>                
            </dt>
            <dd data-rating="<?php echo round($average_ratings/20)?>" <?php if($it >4){?>class="inactive"<?php }?>>
				
                <p class="title"><?php echo (__($_review->getTitle()))?></p>

                <?php if($helper->getRecommend($_review->getReviewId()) == 1){?>     
				<label class="check-recommend"><?php echo __('Yes'); ?>, <?php echo __('I recommend this product'); ?></label>
                <?php }else{?>
                <label class="nocheck-recommend"><?php echo __('No'); ?>, <?php echo __('I do not recommend this product'); ?></label>
                <?php }?>
				<p class="desc"><?php echo nl2br(($_review->getDetail())) ?>    </p>
            </dd>
        <?php endforeach; ?>
        
        </dl>

        <?php if($it >4){?>
        <div id="showallreview"><?php echo __('<span>Load More</span> Reviews')?></div>
        
        <?php }?>
    <?php elseif($block->getParentBlock()): ?>
        <?php echo $block->getParentBlock()->getReviewsSummaryHtml($block->getProduct(), 'short', true)?>
    <?php endif;?>
    <div id="inline1" style="">
    <?php //echo $block->getChildHtml('review_form') ?>
    </div>
</div>
<input type="hidden" id="temp_var" name="temp_var" value="all">



<script type="text/javascript">
require(["jquery","Magento_Ui/js/modal/modal"], function ($,modal) {
	var options = {
                type: 'popup',
                responsive: true,
                innerScroll: true,
                title: 'Write Your Own Review',
                
            };

            var popup = modal(options, $('.block.review-add'));
            $(".review-popup").on('click',function(){ 
                $(".block.review-add").modal("openModal");
            });

jQuery( ".star_ratings" ).click(function() {

    var rating = this.dataset.star;
    jQuery('#temp_var').val(rating);
    if(rating != 'all'){
        jQuery('.review_filter').show();
        jQuery('.value_filter').html(rating+' Star');
    }else{
        jQuery('.review_filter').hide();
    }
    
     

var review_count= jQuery('#review_count').html(jQuery('#value_'+rating).html()+' item(s)');
    var cnt =0;
    jQuery('#dl_review').children('dt,dd').each(function () {  

        if(this.dataset.rating !=rating && rating != 'all'){
            jQuery( this ).hide();
            jQuery( this ).removeClass( "active" );
            jQuery( this ).addClass( "inactive" );
        }else if(rating == 'all'){
            jQuery( this ).show();
            jQuery( this ).removeClass( "active" );            
            jQuery( this ).removeClass( "inactive" );
             cnt = parseInt(cnt)+1;
                if(cnt >8){
                    jQuery( this ).addClass( "inactive" );
                    jQuery( "#showallreview").show();
                }else{
                    jQuery( "#showallreview").hide();
                }
        }
        else{
            cnt = parseInt(cnt)+1;
            jQuery( this ).show();
            jQuery( this ).removeClass( "inactive" );
            if(cnt >8){
                jQuery( this ).addClass( "active" );
                jQuery( "#showallreview").show();
            }else{
                    jQuery( "#showallreview").hide();
                }
        }

    });
     jQuery('.inactive').hide();
     jQuery('.active').hide();
    });

    jQuery.noConflict();
        jQuery(document).ready(function() {
            
            //jQuery('.fancybox').fancybox();
            jQuery('.inactive').hide();
            jQuery('#value_all').hide();
            jQuery('.review_filter').hide();
            
        });
        
        jQuery( "#showallreview" ).click(function() {
            
            
            if(jQuery('#temp_var').val() !='all')
                jQuery('.active').slideToggle('slow');    
            else
               jQuery('.inactive').slideToggle('slow');    

            jQuery( this ).toggleClass( "reviewhide" );

            if(jQuery(this).hasClass("reviewhide")){
                jQuery('#showallreview span').html('COLLAPSE');
                jQuery("html, body").animate({scrollTop: jQuery('.inactive').position().top}, 'slow');
            }else{                
                jQuery('#showallreview span').html('Load More'); 
                 jQuery("html, body").animate({scrollTop: jQuery('#dl_review').position().top}, 'slow');
            }
        
           
        });
       
    });    
    </script>


