
<meta property="og:type" content="website"/>
<meta property="og:title" content="Homescapes – Bettwaren, Heimtextilien, Dekoartikel"/>
<meta property="og:description" content="Der neue Online Shop für exklusive Bettwäsche, Kopfkissen und Bettdecken, Küchentextiilien, Badwaren, Teppiche und Wohnaccessoires. Jetzt stöbern!"/>
<meta property="og:url" content="<?php echo $block->getUrl('contact'); ?>"/>
<meta property="og:site_name" content="Homescapes"/>
<meta property="og:image" content="https://smhttp-ssl-82676-media.nexcesscdn.net/pub/media/og_image/default/homescapes_fullsize.jpg"/>
<meta property="og:image:width" content="512"/>
<meta property="og:image:height" content="512"/>
<meta property="twitter:card" content="summary_large_image"/>
<meta property="twitter:site" content="HomescapesUK"/>
<meta property="twitter:title" content="Homescapes – Bettwaren, Heimtextilien, Dekoartikel"/>
<meta property="twitter:description" content="Der neue Online Shop für exklusive Bettwäsche, Kopfkissen und Bettdecken, Küchentextiilien, Badwaren, Teppiche und Wohnaccessoires. Jetzt stöbern!"/>
