<?php
/*$products = $block->getLoadedProductCollection();
if(count($products)){
	$topProducts = array();
	$i = 0;
	foreach($products as $product){
		if($i >= 5){
			break;
		}
		$topProducts[] = '"'.$product->getSku().'"';
		$i++;
	}
$topSkus = implode($topProducts,',');*/

$category = $block->getCurrentCategory();
$categoryName = $category->getName();

$parentCategoryName = $this->helper('Homescapes\Fbpixel\Helper\Data')->getParentCategoryName($category);

?>
<script type="text/javascript">
	fbq('trackCustom', 'ViewCategory', {
	  content_name: '<?php  echo $categoryName ?>',
	  content_category: '<?php  echo $parentCategoryName ?>',	  
	  content_type: 'product'
	});
</script>
<?php // } ?>