<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/**
 * Grouped product data template
 *
 * @var $block \Magento\Catalog\Block\Product\View\BaseImage
 * @var $block \Magento\GroupedProduct\Block\Product\View\Type\Grouped
 */
?>
<?php $block->setPreconfiguredValue(); ?>
<?php $_product = $block->getProduct(); ?>
<?php $_associatedProducts = $block->getAssociatedProducts(); ?>
<?php $_hasAssociatedProducts = count($_associatedProducts) > 0; ?>
<?php $newprice = array();?>

<div class="table-wrapper grouped">
    <table class="table data grouped" id="super-product-table">
        <caption class="table-caption"><?= /* @escapeNotVerified */ __('Grouped product items') ?></caption>
        <thead>
        <tr  class="g-head">
            <th class="col item" scope="col"><?= /* @escapeNotVerified */ __('Product Name') ?></th>
            <th class="col price" scope="col"><?= /* @escapeNotVerified */ __('Price') ?></th>
            <?php if ($_product->isSaleable()): ?>
                <th class="col qty" scope="col"><?= /* @escapeNotVerified */ __('Qty') ?></th>
            <?php endif; ?>
        </tr>
        </thead>

        <?php if ($_hasAssociatedProducts): ?>
        <?php foreach ($_associatedProducts as $_item): ?>
        <tbody>
            <tr>
                <td data-th="<?= $block->escapeHtml(__('Product Name')) ?>" class="col item">                    
                    <strong class="product-item-name"><?= $block->escapeHtml($_item->getAttributeText('size')) ?></strong>                    
                </td>
                <?php 
                    $finalPrice = $_item->getPriceInfo()->getPrice('final_price')->getAmount()->getBaseAmount();
                    $newprice[]=$finalPrice;
                    ?>                    
                <td data-th="<?= $block->escapeHtml(__('Price')) ?>" class="col price">
					<div class="g-price">
                    <?php if ($block->getCanShowProductPrice($_product)): ?>
                        <?php if ($block->getCanShowProductPrice($_item)): ?>
                            <?= /* @escapeNotVerified */ $block->getProductPrice($_item) ?>
                            <span class="g-discount"><?php echo  $percentage = $this->helper('Homescapes\Completelook\Helper\Data')->DisplayDiscount($_item); ?></span>
                        <?php endif; ?>
                     <?php endif; ?>
					</div>
					
                </td>
                <?php if ($_product->isSaleable()): ?>
                <td data-th="<?= $block->escapeHtml(__('Qty')) ?>" class="col qty">
                <?php if ($_item->isSaleable()) : ?>
                    <div class="control qty" data-mage-init='{
                                        "qtyInput":{"qtyInputSelector": "#qty-<?php /* @escapeNotVerified */ echo $_item->getId() ?>",
                                        "qtyIncrementSelector":"#inc-qty-<?php /* @escapeNotVerified */ echo $_item->getId() ?>",
                                        "qtyDecrementSelector":"#dec-qty-<?php /* @escapeNotVerified */ echo $_item->getId() ?>"
                                        }
                                    }'>
                        <div class="decreaseQty" id="dec-qty-<?php /* @escapeNotVerified */ echo $_item->getId() ?>" >-</div>
                        <input type="number"
                               name="super_group[<?= /* @escapeNotVerified */ $_item->getId() ?>]"
                               data-selector="super_group[<?= /* @escapeNotVerified */ $_item->getId() ?>]"
                               value="<?= /* @escapeNotVerified */ $_item->getQty() * 1 ?>"
                               title="<?= /* @escapeNotVerified */ __('Qty') ?>"
                               class="input-text qty"
                               id="qty-<?php /* @escapeNotVerified */ echo $_item->getId() ?>"
                               data-validate="{'validate-grouped-qty':'#super-product-table'}"
                               data-errors-message-box="#validation-message-box"/>                        
                        <div class="increaseQty" id="inc-qty-<?php /* @escapeNotVerified */ echo $_item->getId() ?>">+</div>
                    </div>
                <?php else: ?>
                    <div class="stock" title="<?= /* @escapeNotVerified */ __('Availability') ?>">
                        <span class="unavailable"><?= /* @escapeNotVerified */ __('Out of stock') ?></span>
                    </div>
                <?php endif; ?>
                </td>
                <?php endif; ?>
            </tr>
            <?php if ($block->getCanShowProductPrice($_product)
                && $block->getCanShowProductPrice($_item)
                && trim($block->getProductPriceHtml(
                    $_item,
                    \Magento\Catalog\Pricing\Price\TierPrice::PRICE_CODE
                ))): ?>
                <tr class="row-tier-price">
                    <td colspan="2">
                        <?= $block->getProductPriceHtml(
                            $_item,
                            \Magento\Catalog\Pricing\Price\TierPrice::PRICE_CODE
                        ) ?>
                    </td>
                </tr>
            <?php endif; ?>
        </tbody>
        <?php endforeach; ?>
        <?php else: ?>
        <tbody>
            <tr>
                <td class="unavailable"
                    colspan="<?php if ($_product->isSaleable()): ?>4<?php else : ?>3<?php endif; ?>">
                    <?= /* @escapeNotVerified */ __('No options of this product are available.') ?>
                </td>
            </tr>
        </tbody>
        <?php endif; ?>
    </table>
</div>
<?php  
    // calculate maxprice and min price for group products
    arsort($newprice);
    $maxprice = reset($newprice);
    $minprice = end($newprice);
    $currencyHelper = $this->helper('Magento\Framework\Pricing\Helper\Data');
 ?>
<?php if($maxprice != $minprice){  ?>
    <div id="group_product_price_<?php echo $_product->getId();  ?>" style="display:none;"><div id="product-price-<?php echo $_product->getId();?>" class="group-prod-price"><?php echo $currencyHelper->currency($minprice,true,false); ?> - <?php echo $currencyHelper->currency($maxprice,true,false);?></div></div>
<?php }else{ ?>
    <div id="group_product_price_<?php echo $_product->getId();  ?>" style="display:none;"><div id="product-price-<?php echo $_product->getId();?>" class="group-prod-price"><?php echo $currencyHelper->currency($minprice,true,false); ?> </div></div>
<?php  } ?>
    <script type="text/javascript">
        require(["jquery","domReady!"], function ($) {
         var productId = "<?php echo $_product->getId();  ?>";
        $(".price-box[data-product-id='"+productId+"'] .price-box").html(jQuery("#group_product_price_"+productId).html());
        });
    </script>
<div id="validation-message-box"></div>
