<?php
/**
 * @author Amasty Team
 * @copyright Copyright (c) 2018 Amasty (https://www.amasty.com)
 * @package Amasty_Shopby
 */
?>
<?php
/** @var \Amasty\Shopby\Block\Navigation\Widget\HideMoreOptions $block */
if ($block->getIsState()) {
    $buttonSelector = "data-am-js='show-more_button_state'";
    $itemSelector = "[data-am-js='shopby-container']";
    $numberUnfoldedOptions = $block->getUnfoldedOptions();
} else {
    $filterSetting = $block->getFilterSetting();
    $filterCode = $block->escapeHtml($filterSetting->getFilterCode());
    $buttonSelector = 'am-filter-items-'.  $filterCode. '-show-more';
    $itemSelector = '.am-filter-items-' . $filterCode;
    $numberUnfoldedOptions = $filterSetting->getNumberUnfoldedOptions();
}
?>
<button class="am-show-more " <?= $buttonSelector ?>
        data-text-more="<?= $block->escapeHtml(__("Show <span class='hide_count'> </span> More"))?>"
        data-text-less="<?= $block->escapeHtml(__("Less"))?>"
        data-is-hide="false">
    <?= $block->escapeHtml(__("Less"))?>
</button>
<script type="text/x-magento-init">
    {
        "<?= $itemSelector ?>": {
            "amShopbyFilterHideMoreOptions": {
                "numberUnfoldedOptions": <?= $block->escapeHtml($numberUnfoldedOptions) ?>,
                "buttonSelector": "[<?= $buttonSelector ?>]",
                "isState": "<?= $block->getIsState() ?>"
            }
        }
    }
</script>
