<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/** @var \Magento\Newsletter\Block\Subscribe $block */

?>


<div class="block container newsletter text-center">
	
	<div class="row">
	
		<div class="col-md">
			
			
			<div class="bottom-icon">
			
				<?php echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('news-gift')->toHtml();?>
			
			</div>
			<div class="news-content">
			
				<h3>Newsletter Sign Up</h3>
				<p>Subscribe to you newsletter for new products, offer & trends. Plus your chance to win £250 gift.</p>

				<div class="content">

					<div class="title"><strong><?= $block->escapeHtml(__('Newsletter')) ?></strong></div>

					<form class="form subscribe"
						novalidate
						action="<?= $block->escapeUrl($block->getFormActionUrl()) ?>"
						method="post"
						data-mage-init='{"validation": {"errorClass": "mage-error"}}'
						id="newsletter-validate-detail">
						<div class="field newsletter">
							<label class="label" for="newsletter"><span><?= $block->escapeHtml(__('Sign Up for Our Newsletter:')) ?></span></label>
							<div class="control">
								<input name="email" type="email" id="newsletter"
											placeholder="<?= $block->escapeHtmlAttr(__('Enter your email address')) ?>"
											data-validate="{required:true, 'validate-email':true}"/>
							</div>
						</div>
						<div class="actions">
							<button class="action subscribe primary" title="<?= $block->escapeHtmlAttr(__('Subscribe')) ?>" type="submit">
								<span><?= $block->escapeHtml(__('Subscribe')) ?></span>
							</button>
						</div>
					</form>
				</div>
			
			</div>
		
				
			
		</div>
		
		<div class="col-md">
			
			
			<?php echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('blog-post')->toHtml();?>
			
		
		</div>
	
	</div>
	
</div>
