
<!-- Pinterest Tag -->

<?php 
$customerEmail='';
$customerData=$block->getCustomerData(); 
if($customerData) {
    //echo 'Customer Id: ' . $customerData->getId() . '<br/>';
    $customerEmail = $customerData->getEmail();
    
}

$objectManager =  '\Magento\Framework\App\ObjectManager'::getInstance();
$context = $objectManager->get('Magento\Framework\App\Http\Context');
$isLoggedIn = $context->getValue(\Magento\Customer\Model\Context::CONTEXT_AUTH);
if($isLoggedIn){
	$customerSession = $objectManager->get('Magento\Customer\Model\SessionFactory')->create();
	//echo "Customer Id L ".$user_id = $customerSession->getCustomer()->getId();
  	$customerEmail = $customerSession->getCustomer()->getEmail();
}

?>

<script>
!function(e){if(!window.pintrk){window.pintrk = function () {
window.pintrk.queue.push(Array.prototype.slice.call(arguments))};var
  n=window.pintrk;n.queue=[],n.version="3.0";var
  t=document.createElement("script");t.async=!0,t.src=e;var
  r=document.getElementsByTagName("script")[0];
  r.parentNode.insertBefore(t,r)}}("https://s.pinimg.com/ct/core.js");
pintrk('load', '2614188572140', {em: '<?php echo $customerEmail ?>'});
pintrk('page');
</script>
<noscript>
<img height="1" width="1" style="display:none;" alt=""
  src="https://ct.pinterest.com/v3/?event=init&tid=2614188572140&pd[em]=<?php echo $customerEmail ?>&noscript=1" />
</noscript>
<!-- end Pinterest Tag -->