<form class="form" action="<?php echo $block->getUrl('newsletters/contact/index'); ?>" id="newsletter_form" method="post">
    <fieldset class="fieldset">
        <div class="field required">
            <label class="label" for="firstname"><span>First Name</span></label>
            <div class="control">
                        <input name="firstname"  id="firstname" title="firstname" value="" class="input-text" type="text" />
            </div>
        </div>

       <div class="field required">
            <label class="label" for="lastname"><span>Last Name</span></label>
            <div class="control">
                        <input name="lastname"  id="lastname" title="lastname" value="" class="input-text" type="text" />
            </div>
        </div>

        <div class="field required">
            <label class="label" for="email"><span>Email</span></label>
            <div class="control">
                        <input name="email"  id="email" title="email" value="" class="input-text" type="text" />
            </div>
        </div>

    </fieldset>
    
    <div class="actions-toolbar">
            <div class="primary">
                    <button type="submit" title="Submit" class="action submit primary">
                        <span>Submit</span>
                    </button>
            </div>
    </div>
  
</form>




<script type="text/javascript">
    require(['jquery', 'mage/mage'], function($){
        var dataForm = $('#newsletter_form');
        dataForm.mage('validation', {
            "rules": {
                "firstname": {
                    "required": true
                },
                "lastname": {
                    "required": true
                },
                "email": {
                    "required": true,
                    "email": true
                }
            }
        });
    });
</script>