
<div class="container newsletter-landing">
	
	<div class="row form-section">
			
		<div class="col-md">
			<div class="newsletter-banner">
				<?php echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('Newsletter-landing-banner')->toHtml();?>
			</div>
		</div>

		<div class="col-md">
			<form class="form" action="<?php echo $block->getUrl('newsletters/contact/index'); ?>" id="newsletter_form" method="post">
				<fieldset class="fieldset">
					<div class="field required">
						<label class="label" for="firstname"><span><?php echo __('First Name') ?></span></label>
						<div class="control">
									<input name="firstname"  id="firstname" title="firstname" value="" class="input-text" type="text" />
						</div>
					</div>

				   <div class="field required">
						<label class="label" for="lastname"><span><?php echo __('Last Name') ?></span></label>
						<div class="control">
									<input name="lastname"  id="lastname" title="lastname" value="" class="input-text" type="text" />
						</div>
					</div>

					<div class="field required">
						<label class="label" for="email"><span><?php echo __('Email') ?></span></label>
						<div class="control">
									<input name="email"  id="email" title="email" value="" class="input-text" type="text" />
						</div>
					</div>
					<div class="field required">
						<div class="control">
							<input name="accept"  class="checkbox required" id="accept" title="accept terms & conditions" value=""  type="checkbox" /> <p><?php echo __('I consent to receive weekly marketing emails with personalised offers, early leaflet previews, fress prize draws & more.') ?>*</p>
						</div>
						
					</div>

				</fieldset>

				<div class="actions-toolbar">
						<div class="primary">
								<button type="submit" title="Submit" class="action submit primary">
									<span>Submit</span>
								</button>
						</div>
				</div>

			</form>
		</div>
			
	</div>
	
	
	<div class="bottom-section">
	
		<?php echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('newsletter-offers-and-conditions')->toHtml();?>
	
	</div>


</div>

<script type="text/javascript">
    require(['jquery', 'mage/mage'], function($){
        var dataForm = $('#newsletter_form');
        dataForm.mage('validation', {
            "rules": {
                "firstname": {
                    "required": true
                },
                "lastname": {
                    "required": true
                },
                "email": {
                    "required": true,
                    "email": true
                }
            }
        });
    });
</script>