
<meta property="og:type" content="website"/>
<meta property="og:title" content="Homescapes - Linge de lit, de bain, de table, Rideaux, Tapis, Déco &amp; rangement"/>
<meta property="og:description" content="Homescapes, c’est un large choix d’articles pour la maison linge de lit, de bain, de table, rideaux, tapis, rangement et objets déco."/>
<meta property="og:url" content="<?php echo $block->getUrl('contact'); ?>"/>
<meta property="og:site_name" content="Homescapes"/>
<meta property="og:image" content="https://smhttp-ssl-82676-media.nexcesscdn.net/pub/media/og_image/default/homescapes_fullsize.jpg"/>
<meta property="og:image:width" content="512"/>
<meta property="og:image:height" content="512"/>
<meta property="twitter:card" content="summary_large_image"/>
<meta property="twitter:site" content="HomescapesUK"/>
<meta property="twitter:title" content="Homescapes - Linge de lit, de bain, de table, Rideaux, Tapis, Déco &amp; rangement"/>
<meta property="twitter:description" content="Homescapes, c’est un large choix d’articles pour la maison linge de lit, de bain, de table, rideaux, tapis, rangement et objets déco."/>
