<?php
/**
 * Copyright © 2018 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */
$_product = $block->getProduct();

$staticBlock = $_product->getAttributeText('m2o_help_hub') ? $_product->getAttributeText('m2o_help_hub') : 'm2o-help-hub' ;
?>

<?php echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId($staticBlock)->toHtml();?>


<?php echo "help hub"?>