<?php
/**
 * Copyright © 2018 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

?>

<div class="container product-sizing">
	<div class="row">
		
		<div class="col-md">
			
			<a><i class="fas fa-book"></i> Buying Guide</a>
			
			<?php include ($block->getTemplateFile('Magento_Catalog::product_sizing.phtml')) ?>
			
			<a><i class="fas fa-play-circle"></i> See in Action</a>
			
		</div>
		
	</div>
	
</div>
