<?php
/**
 * Copyright © 2018 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

?>


<a onclick="openNav()"><i class="fas fa-play-circle"></i> See in Action</a> 


<div id="Product-Video" class="sidenav">
	
	<a href="javascript:void(0)" class="closebtn" onclick="closeNav()"><i class="fas fa-chevron-left"></i> Back</a>
	
	<div class="card-body">
	
		<?php echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('product-sizing')->toHtml();?>
	
	</div>
</div>






<script>
	function openNav() {
		document.getElementById("Product-Video").style.width = "650px";
	}

	function closeNav() {
		document.getElementById("Product-Video").style.width = "0";
	}
</script>