<?php
/**
 * Copyright © 2016 MageWorx. All rights reserved.
 * See LICENSE.txt for license details.
 */
?>
<script>
    require([
        'jquery',
        'optionInventory',
        'uiRegistry'
    ], function ($, optionInventory, registry) {
        var optionBase = registry.get('mageworxOptionBase');
        if (optionBase) {
            optionBase.addUpdater(30, optionInventory(<?php echo $block->getJsonData();?>));
        } else {
            var updaters = registry.get('mageworxOptionUpdaters');
            if (!updaters) {
                updaters = {};
            }
            updaters[30] = optionInventory(<?php echo $block->getJsonData();?>);
            registry.set('mageworxOptionUpdaters', updaters);
        }
    });
</script>
