<?php
/**
 * Copyright © 2018 MageWorx. All rights reserved.
 * See LICENSE.txt for license details.
 */
/** @var \MageWorx\OptionFeatures\Block\Features $block */
?>
<script>
    require([
        'jquery',
        'optionFeatures',
        'optionFeaturesIsDefault',
        'uiRegistry'
    ], function ($, optionFeatures, optionFeaturesIsDefault, registry) {
        var optionBase = registry.get('mageworxOptionBase');
        if (optionBase) {
            optionBase.addUpdater(
                10,
                optionFeatures(<?php echo $block->getJsonData();?>)
            );
            optionBase.addUpdater(
                50,
                optionFeaturesIsDefault(<?php echo $block->getIsDefaultJsonData('frontend');?>)
            );
        } else {
            var updaters = registry.get('mageworxOptionUpdaters');
            if (!updaters) {
                updaters = {};
            }
            updaters[10] = optionFeatures(<?php echo $block->getJsonData();?>);
            updaters[50] = optionFeaturesIsDefault(<?php echo $block->getIsDefaultJsonData('frontend');?>);
            registry.set('mageworxOptionUpdaters', updaters);
        }
    });
</script>
