<?php
/**
 * @author Amasty Team
 * @copyright Copyright (c) 2018 Amasty (https://www.amasty.com)
 * @package Amasty_Faq
 */
?>
<?php
/** @var $block \Amasty\Faq\Block\CollectVisits */
?>
<script>
    require([
        'jquery'
    ], function ($) {
        var options = <?= $block->getStatData(); ?>,
            url = '<?= $block->getStatUrl(); ?>';
        $.ajax({
            type: "GET",
            data: options,
            url: url,
            dataType: 'json'
        });
    });

</script>
