<?php 

$swatchsession=$block->getHomescapessampleswatch();
$finalsampleswatchsession = array();
$sampleCount = '';

if($swatchsession!='')
$finalsampleswatchsession=explode(',',$swatchsession);
if(is_array($finalsampleswatchsession)){
        $sampleCount = count($finalsampleswatchsession);
    }

?>



            <div class="page-title category-title">
            <h1><?php echo __('Order Swatch') ?></h1>
        </div>


<div class="sample-view">
  <form data-mage-init='{"validation":{}}' action="<?php echo $block->getUrl('orderswatches/index/add'); ?>" id="request_form" method="post" name="request_form" onsubmit="return sendOrderSwatch()">
  <input type="hidden" name="requestproduct_id" value="<?php echo $swatchsession; ?>"/>
  <input type="hidden" id="product_sku" name="product_sku" value=""/>
  <input name="sample_count" id="sample_count" value="<?php echo $sampleCount; ?>" type="hidden">
 <!--Second Column-->
    <div class="rightdiv">
      <h2 class="sample-caption info-sample"><?php echo __('My Swatches') ?></h2>           
        <div class="form-panel">
        <div class="inner-panel swatches">
          <?php           
         if(isset($finalsampleswatchsession) && count($finalsampleswatchsession)>0)
         {
            foreach ($finalsampleswatchsession as $key => $value) 
            {
              $_product = $block->getLoadProduct($value);
              ?>
              <div class="swatch-items" id="sampleProduct<?php echo $value;?>">
                <div class="media sample-container">
                  <div class="media-left">
                    <a href="<?php echo $_product->getProductUrl(); ?>" title="<?php echo $_product->getName(); ?>">
                      <img alt="" class="media-object" src="<?php echo $block->getsmallImg($_product) ?>" width="105" height="auto" alt="<?php echo $_product->getName(); ?>" title="<?php echo $_product->getName() ?>">
                    </a>
                  </div>
                  <div class="media-body">
                    <?php echo $_product->getName(); ?>
                    <script type="text/javascript">
                    var productsku=document.getElementById('product_sku').value;
                    if(productsku!='')
                    {
                      document.getElementById('product_sku').value=productsku+",<?php echo $_product->getSku() ?>";
                    }
                    else
                    {
                      document.getElementById('product_sku').value="<?php echo $_product->getSku() ?>";
                    }
                    </script>  
                    
                    <div class="sampleitem">
                      <?php echo __('Item: #'); ?> 
                      <strong><?php echo $_product->getSku(); ?></strong>
                 <input type="hidden" value="<?php echo $_product->getSku();?>" id="productSku<?php echo $value;?>" name="productsku[]"/>
                  <input type="hidden" value="<?php echo $value;?>" id="productId<?php echo $value;?>" name="productid[]"/>
                  <input type="hidden" value="<?php echo $_product->getName(); ?>" id="productName<?php echo $value;?>" name="productname[]"/>
                    </div>
                  </div>
                    <a href="javascript:void(0)" data-id="<?php echo $_product->getId();  ?>" data-url="<?php echo $block->getUrl('orderswatches/ajax/removeProductSample') ?>" class="sampleclose-btn"><i class="fa fa-times-circle"></i>
                  </a>
                </div>               
              </div>             
           <?php 
            } 
          }
          else
          {
          ?>
            <div class="swatch-message">             
              <?php echo __('No sample swatches found') ?>
            </div> 
          <?php 
          }
          ?>                                            
        
      </div>
    <div class="swatch-policy">
          <h2 class="sample-heading"><?php echo __('Swatch Policy:') ?></h2>
      <?php echo __('Swatch requests are free.  Orders are limited to 5 swatches per request.  If you require further details please call us on 0121 368 0051') ?>
        </div>
      </div>
    </div>
    <?php /*first form*/?>
  	<div class="form-list">

  	
		<p class="swatch-request"><?php echo __('Swatch Request') ?></p>
		<div class="fill-out"><?php echo __('Please fill out the following information.') ?></div>    	 
		<div class="form-panel">
			<div class="inner-panel">
				<p class="required"><em>*</em><?php echo __('Required Fields') ?></p>				
				<div class="form-group">
					<div class="row">
					  <div class="left-column">
						 <label for="firstname"><?php echo __('First Name') ?><em>*</em></label>
						  <input name="fname" class="form-control required-entry"  size="45" type="text" placeholder="<?php echo __('First Name') ?>" />
					  </div>
					  <div class="right-column">
						 <label for="lastname"><?php echo __('Last Name') ?><em>*</em></label>
						  <input name="lname" class="form-control required-entry"  size="45" type="text" placeholder="<?php echo __('Last Name') ?>" />
					  </div>
					</div>
				
				  <div class="form-group">
					 <label for="emailaddress"><?php echo __('Email address') ?><em>*</em></label>
					 <input name="email_address" placeholder="<?php echo __('Email address') ?>" class="form-control required-entry validate-email" type="text" />
				  </div>
				</div>
			  <div class="form-group">
				 <label for="telephonenumber"><?php echo __('Telephone Number') ?><em>*</em></label>
				 <input name="phone" class="form-control required-entry validate-number" type="text" />
			  </div>
			  <div class="form-group">
				 <label for="addressline1"><?php echo __('Address Line1') ?><em>*</em></label>
				 <textarea rows="1" name="address" class="form-control required-entry"></textarea>
			  </div>
			  <div class="form-group">
				 <label for="addressline2"><?php echo __('Address Line2') ?></label>
				 <textarea rows="1" name="address2" class="form-control"></textarea>      
			  </div>
			  <div class="form-group">
				<div class="row">
				  <div class="left-column">
					 <label for="city"><?php echo __('City') ?><em>*</em></label>
					 <input name="city" class="form-control required-entry" type="text" />
				  </div>
				  <div class="right-column">
					 <label for="county"><?php echo __('County') ?><em>*</em></label>
					 <input name="county" class="form-control required-entry" type="text" />
				  </div>
				 </div>
			  </div>
			  <div class="form-group">
				<div class="row">
				  <div class="left-column">
					 <label for="zippostalcode"><?php echo __('Zip/Postal Code') ?><em>*</em></label>
					 <input type="text" name="zip_code" placeholder="Zip/Postal Code"  class="form-control required-entry" type="text" />
				  </div>
				  <div class="right-column">
					 <label for="country"><?php echo __('Country') ?><em>*</em></label>
           <?php  $countrys=$block->getShipCountry();
           if($countrys!='')
           $countryselected=explode(",",$countrys);
         else
          $countryselected=array();
           ?>
           <?php $_countries = $block->getCountryCollection();
//            echo "<pre/>";
//            print_r($_countries); die('sdfsd');
           ?>
            <?php if (count($_countries) > 0): ?>
			<div class="custom-select">
              <select name="country" id="country" class="form-control required-entry">
                <option value="">-- Please Select --</option>
                <?php foreach($_countries as $_country): ?>
                  <?php if(in_array($_country['value'],$countryselected)){?>
                  <option value="<?php echo $_country['value'] ?>">
                    <?php echo $_country['label'] ?>
                  </option>
                  <?php }?>
                <?php endforeach; ?>
              </select>
			  </div>
            <?php endif; ?>
				  </div>
				 </div>
			  </div>        			  
				<div id="swatcherror" style="display:none;color:#df280a;"></div>
				<button class="btn btn-warning btn-submit" title="<?php echo __('Send my Swatches'); ?>" type="submit"><?php echo __('Send my Swatches') ?></button> 

			</div>
		</div>
    </div>
     
  </form>
</div>
<script type="text/javascript">
 require(['jquery', 'jquery/ui'], function($){ 
     $('.sampleclose-btn').on('click', function(element){
         var samplecountdown=parseInt($('#sample_count').val());    
         var url= $(this).attr('data-url');
                    var productId = $(this).attr('data-id');
                    var request = $.ajax( {
                            url: url ,
                            data: { productId: productId},
                            type: 'POST',
                            showLoader: true,
                            beforeSend: function(){
                                $('.remove-wait'+productId).show();
                                },
                        } );
                        request.done( function (result)
                        {   
                            console.log('----remove product------');                            
                            var json = result;
                            $('#sample_count').val(samplecountdown-1);   
                            $(".order-swatch-verticalcount").html(" ("+$('#sample_count').val()+")");             
                            $('ul#updatedswatches').append(json.html);
                            $( "#sampleProduct"+productId).remove(); 
                            $('.remove-wait'+productId).hide();
                            
                        } );
                        request.fail( function ( error )
                        {
                            console.dir(error);             
                        } );
         
         
     });
 });
</script>
<style>
.krish-orderswatch-index-index .category-title h1 {
  padding: 10px 0 0 0;
  margin: 0;
  clear: both;
}

.sample-view .form-list {
  float: left;
  margin-right: 30px;
  width: 425px;
  padding-top: 20px;
}
.sample-view .form-list h2 {
  color: #1c1c1c;
  font-weight: bold;
  font-size: 24px;
  text-transform: capitalize;
  margin: 0 0 22px;
}
.sample-view .form-list .swatch-request {
  color: #1c1c1c;
  font-weight: bold;
  font-size: 16px;
}
.sample-view .form-list em {
  color: #df280a;
  font-size: 14px;
  font-weight: normal;
}
.sample-view .form-list input {
  margin-top: 2px;
  border-radius: 4px;
}
.sample-view .form-list textarea {
  border-radius: 4px;
  min-height: 70px;
}
.sample-view .form-list label {
  margin-top: 8px;
}
.sample-view .form-list .fill-out {
  color: #404040;
  margin: 4px 0 10px;
}
.sample-view .form-list .form-group {
  float: left;
  width: 100%;
}
.sample-view .form-panel {
  border-top: 1px solid #ccc;
  padding-top: 5px;
}
.sample-view .inner-panel {
  background: #fff;
  padding: 15px 15px 25px;
}
.sample-view .form-group .row .left-column {
  width: 50%;
  float: left;
  padding-right: 10px;
}
.sample-view .form-group .row .right-column {
  width: 50%;
  float: right;
  padding-left: 10px;
}
.sample-view .form-group .custom-select {
  border-radius: 3px;
  height: 32px;
  margin-top: 2px;
  width: 100%;
}
.sample-view .form-group .custom-select select {
  margin-top: 0;
}
.sample-view .rightdiv {
  float: right;
  width: 62%;
  padding-top: 46px;
}
.sample-view .rightdiv .sample-caption {
  background-position: 0 -1268px;
  color: #1c1c1c;
  font-weight: bold;
  font-size: 16px;
  padding-left: 30px;
  line-height: 25px;
  text-transform: capitalize;
}
.sample-view .rightdiv .inner-panel.swatches {
  float: left;
  padding: 32px 0;
  width: 100%;
}
.sample-view .rightdiv .inner-panel.swatches .swatch-items {
  background: #fff none repeat scroll 0 0;
  border: 1px solid #e5e5e5;
  border-radius: 3px;
  box-shadow: 0 3px 3px rgba(0, 0, 0, 0.1);
  float: left;
  margin: 0 25px 25px 0;
  padding: 15px;
  width: 46%;
  position: relative;
}
.sample-view .rightdiv .inner-panel.swatches .media-left {
  float: left;
  margin-right: 18px;
  height: 105px;
  width: 115px;
  overflow: hidden;
}
.sample-view .rightdiv .inner-panel.swatches .media-body {
  float: left;
  line-height: 18px;
  width: 52%;
}
.sample-view .rightdiv .inner-panel.swatches .media-body .sampleitem {
  font-weight: bold;
  font-size: 12px;
  margin-top: 10px;
}
.sample-view .rightdiv .inner-panel.swatches .sampleclose-btn {
  position: absolute;
  right: -10px;
  top: -10px;
}
.sample-view .rightdiv .inner-panel.swatches .sampleclose-btn .fa-times-circle {
  /*background: rgba(0, 0, 0, 0) url("../images/swatch-close.png") no-repeat scroll 0px 0;*/
  background: transparent url("../images/large-close.png") no-repeat scroll 0 0/20px 20px;
  width: 20px;
  height: 20px;
  display: block;
}
.sample-view .rightdiv .inner-panel.swatches .swatch-message {
  background: #e06a6e;
  color: #fff;
  font-weight: bold;
  margin-bottom: 10px;
  opacity: 0.7;
  padding: 5px 10px;
  border-radius: 3px;
}
.sample-view .rightdiv .swatch-policy {
  background: #f7f7f7 url("../images/swatch-policy.png") no-repeat scroll 24px center;
  background-size: 60px auto;
  float: left;
  color: #073147;
  margin-top: 10px;
  padding: 15px 20px 15px 98px;
  width: 100%;
}
.sample-view .rightdiv .swatch-policy .sample-heading {
  color: #073147;
  font-weight: bold;
  font-size: 14px;
  margin-bottom: 5px;
  text-transform: capitalize;
}
.sample-view .btn-submit {
  background: #005dbd;
  border: medium none;
  border-radius: 3px;
  color: #fff;
  font-weight: bold;
  font-size: 15px;
  margin-top: 20px;
  padding: 10px 20px;
  text-transform: uppercase;
}

    
</style>