<div id="header-swatch"></div>

    <style>
        .swatches-dialog {
      background: rgba(47, 47, 47, 0.9);
      left: 0;
      position: fixed;
      top: 0;
      width: 100%;
      z-index: 999;
    }
    .swatches-dialog .inner-section {
      margin: 0 auto;
      max-width: 1090px;
      overflow: hidden;
      padding: 11px 0 9px;
    }
    .swatches-dialog ul li {
      margin-right: 18px;
      padding: 3px;
      position: relative;
      width: 200px;
      background: #f0f0f0;
      float: left;
      height: 56px;
    }
    .swatches-dialog ul li.blankswatch {
      padding: 5px;
    }
    .swatches-dialog ul li.blankswatch .emptydesc {
      border: 1px dashed #ccc;
      color: #bbb;
      padding: 11px 0 12px;
      text-align: center;
    }
    .swatches-dialog ul li img {
      float: left;
      margin-right: 5px;
    }
    .swatches-dialog ul li .desc {
      color: #404040;
      float: left;
      font-size: 12px;
      height: 38px;
      line-height: 16px;
      overflow: hidden;
      padding: 5px 0 0;
      width: 70%;
    }
    .swatches-dialog ul li .remove-swatch {
      display: block;
      height: 28px;
      position: absolute;
      right: -14px;
      top: -14px;
      width: 28px;
      font-size: 0;
      background: url("../images/icon_sprite_new.png") no-repeat -77px -591px;
      background-size: 300px 1300px;
    }
    .swatches-dialog .actions {
      float: right;
      margin-right: 18px;
      padding: 10px 0 0;
    }
    .swatches-dialog .actions .order-sw, .swatches-dialog .actions .btn-close {
      background: #005dbd none repeat scroll 0 0;
      border: medium none;
      border-radius: 3px;
      color: #fff;
      font-weight: bold;
      font-size: 12px;
      padding: 3px 10px;
      text-transform: uppercase;
    }
    .swatches-dialog .actions .order-sw {
      background: #005dbd;
      text-decoration: none;
      height: 24px;
      float: left;
      margin: 0 8px 0 0;
    }
    .swatches-dialog .actions .btn-close {
      background: #e32a37;
    }
    .swatches-dialog #remove-please-wait {
      left: 50%;
      margin: -7px 0 0 -6px;
      position: absolute;
      top: 50%;
    }

    .vertical-swatch {
      position: fixed;
      right: -64px;
      top: 50%;
      z-index: 9999;
      -ms-transform: rotate(-90deg);
      -webkit-transform: rotate(-90deg);
      transform: rotate(-90deg);
    }


    .vertical-swatch .order-swatch-vertical {
      background: #005dbd;
      border: 1px solid #00468f;
      color: #fff;
      font-family: lato;
      padding: 3px 12px;
      text-transform: uppercase;
                    /*&:after {
                            color: #a3a3a3;
                            content: '\f022';
                            display: block;
                            font-family: "FontAwesome";
                            font-size: 18px;
                            font-weight: 300;
                  height: 20px;
                  line-height: 20px;
                            width: 20px;
                    }*/
    }


    </style>