<?php
$currentProduct = $block->getCurrentProduct();
$relatedProducts = $block->getItems();
$displayText = $currentProduct->getAttributeText('related_product_item');

if(count($relatedProducts)){
?>
<div class="choose-color-related-items">
    <?php $displayText = ($displayText ? $displayText : __('Select Product')); ?>
    <span><?php echo $displayText; ?></span>
    <ul>
    <li>    
        <a class="active-pro" href="#"><img src="<?php echo $block->getthumbnailImg($currentProduct); ?>" /></a>
    </li>    
    <?php  foreach($relatedProducts as $relatedProduct){ 
           $_product = $block->getLoadProduct($relatedProduct->getId());
           $product_url = $relatedProduct->getProductUrl();
           if(strpos($product_url, 'category')){
                if($_product->getUrlPath()){
                    $product_url = $this->getUrl().$_product->getUrlPath().'.html';
                }
            }

        ?>         
    <li>    
        <a href="<?php echo $product_url; ?>"  ><img src="<?php echo $block->getthumbnailImg($_product); ?>" /></a>
    </li>
    <?php  } ?>
    </ul>
</div>
<?php } ?>