<?php
$currentProduct = $block->getCurrentProduct();
$relatedProducts = $block->getItems();
$displayText = $currentProduct->getAttributeText('related_product_item');

if(count($relatedProducts)){
?>
<div class="choose-color-related-items">
    <?php $displayText = ($displayText ? $displayText : __('Choose Color')); ?>
    <span><?php echo $displayText; ?></span>
    <ul>
    <li>    
        <a class="active-pro" href="#"><img src="<?php echo $block->getthumbnailImg($currentProduct); ?>" /></a>
    </li>    
    <?php  foreach($relatedProducts as $relatedProduct){ 
           $_product = $block->getLoadProduct($relatedProduct->getId()); 
        ?>         
    <li>    
        <a href="<?php echo $_product->getProductUrl(); ?>"  ><img src="<?php echo $block->getthumbnailImg($_product); ?>" /></a>
    </li>
    <?php  } ?>
    </ul>
</div>
<?php } ?>