<?php 
$currentProduct = $block->getCurrentProduct();
$displayText = $currentProduct->getAttributeText('complete_look_title');
$completeLookProducts = $block->getCompletelookProducts();
    if(is_array($completeLookProducts)){  ?>  
    <div class="complete-look">
        <?php $displayText = ($displayText ? $displayText : __('Complete Look')); ?>
        <span><?php echo  $displayText; ?></span>
        <div class="complete-look">
    <?php  foreach($completeLookProducts as $completeLookProduct)
        {        
            $_product = $block->getLoadProduct($completeLookProduct);
            ?>

                <form data-product-sku="<?= $block->escapeHtml($_product->getSku()) ?>"
          action="<?= /* @NoEscape */ $block->getSubmitUrl($_product) ?>" method="post"
          id="product_addtocart_form_<?= $block->escapeHtml($_product->getSku()) ?>"<?php if ($_product->getOptions()): ?> enctype="multipart/form-data"<?php endif; ?>>
                <input type="hidden" name="product" value="<?= /* @escapeNotVerified */ $_product->getId() ?>" />
                <input type="hidden" name="selected_configurable_option" value="" />
                <?= $block->getBlockHtml('formkey') ?>
                <div class="product-info">
                    <div class="product-img"><img src="<?php echo $block->getImageUrl($_product); ?>" title="<?php echo $_product->getName() ?>" /></div>
                    <div class="product-name-price">
                        <span class="name"><?php echo $_product->getName(); ?></span>
                        <span class="price"><?php echo $_product->getPrice(); ?></span>
                        <a href="<?php echo $_product->getProductUrl(); ?>" title="<?php echo __('Description'); ?>"><?php echo __('Description'); ?></a>
                    </div>
                </div>
            
            <?php if($_product->getTypeId()=='grouped'){ // check product type is group 
                     $_associatedProducts = $block->getAssociatedProducts($_product);                      
                     $_hasAssociatedProducts = count($_associatedProducts) > 0; ?> 
                <div class="table-wrapper grouped">
                    <table class="table data grouped" id="super-product-table-<?php echo $_product->getSku(); ?>">
                        <caption class="table-caption"><?= /* @escapeNotVerified */ __('Grouped product items') ?></caption>
                        <thead>
                        <tr>
                            <th class="col item" scope="col"><?= /* @escapeNotVerified */ __('Product Name') ?></th>
                            <th class="col item" scope="col"><?= /* @escapeNotVerified */ __('Price') ?></th>
                            <?php if ($_product->isSaleable()): ?>
                                <th class="col qty" scope="col"><?= /* @escapeNotVerified */ __('Qty') ?></th>
                            <?php endif; ?>
                        </tr>
                        </thead>
                        <?php if ($_hasAssociatedProducts){ ?>
                            <?php foreach ($_associatedProducts as $_item){ ?>
                            <tbody>
                                <tr>
                                    <td data-th="<?= $block->escapeHtml(__('Product Name')) ?>" class="col item">
                                        <strong class="product-item-name"><?= $block->escapeHtml($_item->getAttributeText('size')) ?></strong>                                                                                
                                    </td>
                                    <td data-th="<?= $block->escapeHtml(__('Price')) ?>" class="col item">
                                        <?php if ($block->getCanShowProductPrice($_product)): ?>
                                            <?php if ($block->getCanShowProductPrice($_item)): ?>
                                                <?= /* @escapeNotVerified */ $block->getProductPrice($_item) ?>
                                            <?php endif; ?>
                                         <?php endif; ?>
                                    </td>
                                    <?php if ($_product->isSaleable()): ?>
                                    <td data-th="<?= $block->escapeHtml(__('Qty')) ?>" class="col qty">
                                    <?php if ($_item->isSaleable()) : ?>
                                        
                                        <div class="control qty" data-mage-init='{
                                        "qtyInput":{"qtyInputSelector": "#qty-<?php /* @escapeNotVerified */ echo $_item->getId() ?>",
                                        "qtyIncrementSelector":"#inc-qty-<?php /* @escapeNotVerified */ echo $_item->getId() ?>",
                                        "qtyDecrementSelector":"#dec-qty-<?php /* @escapeNotVerified */ echo $_item->getId() ?>"
                                        }
                                    }'>     
                                            <div class="decreaseQty" id="dec-qty-<?php /* @escapeNotVerified */ echo $_item->getId() ?>" >-</div>
                                            <input type="number"
                                                   name="super_group[<?= /* @escapeNotVerified */ $_item->getId() ?>]"
                                                   data-selector="super_group[<?= /* @escapeNotVerified */ $_item->getId() ?>]"
                                                   value="<?= /* @escapeNotVerified */ $_item->getQty() * 1 ?>"
                                                   title="<?= /* @escapeNotVerified */ __('Qty') ?>"
                                                   class="input-text qty"
                                                   id="qty-<?php /* @escapeNotVerified */ echo $_item->getId() ?>"
                                                   data-validate="{'validate-grouped-qty':'#super-product-table-<?php echo $_product->getSku(); ?>'}"
                                                   data-errors-message-box="#validation-message-box-<?php echo $_product->getSku(); ?>"/>                                            
                                            <div class="increaseQty" id="inc-qty-<?php /* @escapeNotVerified */ echo $_item->getId() ?>">+</div>
                                        </div>
                                    <?php else: ?>
                                        <div class="stock unavailable" title="<?= /* @escapeNotVerified */ __('Availability') ?>">
                                            <span><?= /* @escapeNotVerified */ __('Out of stock') ?></span>
                                        </div>
                                    <?php endif; ?>
                                    </td>
                                    <?php endif; ?>
                                </tr>
                                <?php if ($block->getCanShowProductPrice($_product)
                                    && $block->getCanShowProductPrice($_item)
                                    && trim($block->getProductPriceHtml(
                                        $_item,
                                        \Magento\Catalog\Pricing\Price\TierPrice::PRICE_CODE
                                    ))): ?>
                                    <tr class="row-tier-price">
                                        <td colspan="2">
                                            <?= $block->getProductPriceHtml(
                                                $_item,
                                                \Magento\Catalog\Pricing\Price\TierPrice::PRICE_CODE
                                            ) ?>
                                        </td>
                                    </tr>
                                <?php endif; ?>
                            </tbody>
                            <?php  } ?>
                        <?php  } ?>
                    </table>
                </div>
                <div id="validation-message-box-<?php echo $_product->getSku(); ?>"></div>
                <div class="actions">
                    <button type="submit"
                            title="<?=   __('Add to Cart'); ?>"
                            class="action primary tocart"
                            id="product-addtocart-button-<?php echo $_product->getSku() ?>">
                        <span><?= /* @escapeNotVerified */  __('Add to Cart'); ?></span>
                    </button>
                    <?= $block->getChildHtml('', true) ?>
                </div>
            <?php }elseif ($_product->getTypeId() == 'simple') { ?>
                <div class="box-tocart">
                    <div class="fieldset">
                        <div class="field qty">
                            <label class="label" for="qty"><span><?= /* @escapeNotVerified */ __('Qty') ?></span></label>
                            <div class="control" data-mage-init='{
                                        "qtyInput":{"qtyInputSelector": "#qty-<?php /* @escapeNotVerified */ echo $_product->getId() ?>",
                                        "qtyIncrementSelector":"#inc-qty-<?php /* @escapeNotVerified */ echo $_product->getId() ?>",
                                        "qtyDecrementSelector":"#dec-qty-<?php /* @escapeNotVerified */ echo $_product->getId() ?>"
                                        }
                                    }'>
                                <div class="decreaseQty" id="dec-qty-<?php /* @escapeNotVerified */ echo $_product->getId() ?>" >-</div>
                                <input type="number"
                                       name="qty"                                       
                                       value="<?= /* @escapeNotVerified */ $block->getProductDefaultQty() * 1 ?>"
                                       title="<?= /* @escapeNotVerified */ __('Qty') ?>"
                                       class="input-text qty"
                                       id="qty-<?php /* @escapeNotVerified */ echo $_product->getId() ?>"
                                       data-validate="<?= $block->escapeHtml(json_encode($block->getQuantityValidators())) ?>"
                                       />
                                <div class="increaseQty" id="inc-qty-<?php /* @escapeNotVerified */ echo $_product->getId() ?>">+</div>   
                            </div>
                        </div>
                    </div>
                </div>
                <div class="actions">
                    <button type="submit"
                            title="<?= /* @escapeNotVerified */ __('Add to Cart'); ?>"
                            class="action primary tocart"
                            id="product-addtocart-button-<?php echo $_product->getSku() ?>">
                        <span><?= /* @escapeNotVerified */ __('Add to Cart'); ?></span>
                    </button>
                    <?= $block->getChildHtml('', true) ?>
                </div>
                
            <?php } // end check product type 
            ?>
            
                    <script type="text/x-magento-init">
                    {
                        "#product_addtocart_form_<?php echo $_product->getSku() ?>": {
                            "Magento_Catalog/js/validate-product": {}
                        }
                    }
                </script>
                </form>
        <?php } ?>
                </div>
        </div>
    <?php }  
    
?>


