<?php 
$currentProduct = $block->getCurrentProduct();
$displayText = $currentProduct->getAttributeText('complete_look_title');
$completeLookProducts = $block->getCompletelookProducts();
$buttonTitle = __('Add to Cart'); 
    if(is_array($completeLookProducts)){  ?>  


    <div class="complete-look">
        <?php $displayText = ($displayText ? $displayText : __('Complete The Look')); ?>
		
		<h3 class="section-title text-center">
		
        	<span><?php echo  $displayText; ?></span>
			
		</h3>
		
        <div class="conf-products">
    <?php  foreach($completeLookProducts as $completeLookProduct)
        {        
            $_product = $block->getLoadProduct($completeLookProduct);            
            $priceRange = array();
            ?>                
            
                <form data-product-sku="<?= $block->escapeHtml($_product->getSku()) ?>"
          action="<?= /* @NoEscape */ $block->getAddToCartUrlForProduct($_product) ?>" method="post"
          id="product_addtocart_form_<?= $block->escapeHtml($_product->getSku()) ?>"<?php if ($_product->getOptions()): ?> enctype="multipart/form-data"<?php endif; ?>>
					
					
                <input type="hidden" name="product" value="<?= /* @escapeNotVerified */ $_product->getId() ?>" />
                <input type="hidden" name="selected_configurable_option" value="" />
					
                <?= $block->getBlockHtml('formkey') ?>
                <div class="selection-product-price-<?php echo $_product->getId(); ?>" >
					
					<div class="product-info">
						<div class="product-img"><a href="<?php echo $_product->getProductUrl(); ?>"><img src="<?php echo $block->getImageUrl($_product); ?>" title="<?php echo $_product->getName() ?>" /></a></div>
						
						
						<div class="product-name-price">
							<span class="name"><a href="<?php echo $_product->getProductUrl(); ?>"><?php echo $_product->getName(); ?></a></span>
							<div class="product-info-price">
								<?php echo $block->getProductPrice($_product); ?>
                                                                <span class="g-discount">
                                                                    <?php echo  $percentage = $this->helper('Homescapes\Completelook\Helper\Data')->DisplayDiscount($_product); ?>
								</span>
							</div>
							<a class="des-link" href="javascript:void(0)" onclick="openDescription('description-<?php echo $_product->getId(); ?>')" title="<?php echo __('Description'); ?>">
								
								<?php echo __('Description'); ?> <i class="fas fa-chevron-right"></i>
								
							</a>
							
							<?php $reviews = ''; ?>
							<?php $_items = $block->getReviewsCollection($_product)->getItems();  //foreach ($_items as $rating_review){ echo "<pre>"; print_r(count($rating_review->getRatingVotes())); die('ffff');   exit; } ?>
							<?php echo $reviews = $block->getReviewsSummaryHtml($_product) ?>
							<?php // echo $reviews = $block->getCustomReviewsSummaryHtml($_product,false,false,$_items) ?>
							
							<div id="description-<?php echo $_product->getId(); ?>" class="sidenav">
								
								<!--back close button-->
								
								<a href="javascript:void(0)" class="closebtn" onclick="closeDescription('description-<?php echo $_product->getId(); ?>')"><i class="fas fa-times"></i> Close</a>
								
								<!--product name-->
								
								<h2><?php echo $_product->getName(); ?></h2>
								
								<!--details and decription accordian-->
								
								
								
								<div id="caccordion" role="tablist">
									
									
									<!--Description-->

								    <div class="card" id="one">
										<div class="card-header " role="tab" id="headingOne">

                                                                                    <a data-toggle="collapse"   href="#collapseOne-<?php echo $_product->getId(); ?>" aria-expanded="true" aria-controls="collapseOne-<?php echo $_product->getId(); ?>">
											  <h5>
												  <?php echo __('Product Description') ?>

											  </h5>
											 </a> 
										</div>

										<div id="collapseOne-<?php echo $_product->getId(); ?>" class="collapse show" role="tabpanel" aria-labelledby="headingOne" data-parent="#caccordion">
											<div class="card-body">
											
												<?php echo $_product->getDescription(); ?>
											
											</div>
										</div>
									</div>
									
									
									<!--Product Specifications-->

									<div class="card" id="two">
										<div class="card-header " role="tab" id="headingTwo">
										  <a class="collapsed" data-toggle="collapse" href="#collapseTwo-<?php echo $_product->getId(); ?>" aria-expanded="false" aria-controls="collapseTwo-<?php echo $_product->getId(); ?>">
											<h5>

											 <?php echo __('Product Specifications') ?>

											</h5>
										  </a>
										</div>
										<div id="collapseTwo-<?php echo $_product->getId(); ?>" class="collapse" role="tabpanel" aria-labelledby="headingTwo" data-parent="#caccordion">
											<div class="card-body">
											
												<?php echo $this->getLayout()->createBlock("Magento\Framework\View\Element\Template")->setProductAtt($_product)->setTemplate("Homescapes_Completelook::product/view/attribute.phtml")->toHtml();?> 
											
											</div>

										</div>
									</div>
									
									<?php  if(count($_items)){  ?>
									<!--Rating and reviews-->
									
									<div class="card" id="three">
										<div class="card-header " role="tab" id="headingThree">
											 <a class="collapsed" data-toggle="collapse" href="#collapseThree-<?php echo $_product->getId(); ?>" aria-expanded="false" aria-controls="collapseThree-<?php echo $_product->getId(); ?>">
												<h5>

												  <?php echo __('Rating & Reviews') ?>

											  </h5>
											 </a>
										</div>
										<div id="collapseThree-<?php echo $_product->getId(); ?>" class="collapse" role="tabpanel" aria-labelledby="headingThree" data-parent="#caccordion">
											<div class="card-body">
											
												<?php echo $this->getLayout()->createBlock("Magento\Framework\View\Element\Template")->setProductRewiews($_items)->setTemplate("Homescapes_Completelook::product/view/reviews.phtml")->toHtml();?>
											
											</div>
										</div>
									</div>
									<?php }  ?>
									<!--Delivery-->

									<div class="card" id="four">
										<div class="card-header " role="tab" id="headingFour">
											<a data-toggle="collapse" class="collapsed" href="#collapseFour-<?php echo $_product->getId(); ?>" aria-expanded="false" aria-controls="collapseFour-<?php echo $_product->getId(); ?>">	
												<h5>
													
												  <?php echo __('Delivery') ?>

											  </h5>
											</a>
										</div>
										<div id="collapseFour-<?php echo $_product->getId(); ?>" class="collapse" role="tabpanel" aria-labelledby="headingFour" data-parent="#caccordion">
										  <div class="card-body">
											  
												<?php $staticBlock = $_product->getAttributeText('delivery_block') ? $_product->getAttributeText('delivery_block') : 'delivery'; ?>
											  
												<?php echo $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId($staticBlock)->toHtml(); ?>
											  
										  </div>
										</div>
									</div>
		
									
									<!--Return-->

									<div class="card" id="five">
										<div class="card-header " role="tab" id="headingfive">
										  <a class="collapsed" data-toggle="collapse" href="#collapsefive-<?php echo $_product->getId(); ?>" aria-expanded="false" aria-controls="collapsefive-<?php echo $_product->getId(); ?>">
											<h5>

											 <?php echo __('Returns') ?>

											</h5>
										  </a>
										</div>
										<div id="collapsefive-<?php echo $_product->getId(); ?>" class="collapse" role="tabpanel" aria-labelledby="headingfive" data-parent="#caccordion">
										  <div class="card-body">
											  
												<?php echo $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('returns')->toHtml(); ?>
											  
										  </div>
										</div>
									</div>
									
									
								</div>
								
								
								
							</div>
							
							
						</div>
						
						
						
					</div>
					
                </div>    
            
            <?php if($_product->getTypeId()=='grouped'){ // check product type is group 
                     $_associatedProducts = $block->getAssociatedProducts($_product);                      
                     $_hasAssociatedProducts = count($_associatedProducts) > 0; ?> 
                <div class="table-wrapper group-pro grouped">
                    <table class="table data grouped" id="super-product-table-<?php echo $_product->getSku(); ?>">
                        <caption class="table-caption"><?= /* @escapeNotVerified */ __('Grouped product items') ?></caption>
                        <thead>
                        <tr class="g-head">
                            <th class="col item" scope="col"><?= /* @escapeNotVerified */ __('Product Name') ?></th>
                            <th class="col price" scope="col"><?= /* @escapeNotVerified */ __('Price') ?></th>
                            <?php // if ($_product->isSaleable()): ?>
                                <th class="col qty" scope="col"><?= /* @escapeNotVerified */ __('Qty') ?></th>
                            <?php // endif; ?>
                        </tr>
                        </thead>
                        <?php if ($_hasAssociatedProducts){ ?>
                            <?php foreach ($_associatedProducts as $_item){ ?>
                            <tbody>
                                <tr class="g-price">
                                    <td data-th="<?= $block->escapeHtml(__('Product Name')) ?>" class="col item">
                                        <strong class="product-item-name"><?= $block->escapeHtml($_item->getAttributeText('size')) ?></strong>                                                                                
                                    </td>
                                    <?php   // code for price range 
                                            $finalPrice = $_item->getPriceInfo()->getPrice('final_price')->getAmount()->getBaseAmount();
                                            $priceRange[]=$finalPrice; ?>             
                                    <td data-th="<?= $block->escapeHtml(__('Price')) ?>" class="col price">
                                        <?php if ($block->getCanShowProductPrice($_product)): ?>
                                            <?php if ($block->getCanShowProductPrice($_item)): ?>
                                                <?= /* @escapeNotVerified */ $block->getProductPrice($_item) ?>
                                          
											<span class="g-discount">
												<?php echo  $percentage = $this->helper('Homescapes\Completelook\Helper\Data')->DisplayDiscount($_item); ?>
										    </span>
										
                                            <?php endif; ?>
                                         <?php endif; ?>
                                    </td>
                                    <?php // if ($_product->isSaleable()): ?>
                                    <td data-th="<?= $block->escapeHtml(__('Qty')) ?>" class="col qty">
                                    <?php if ($_item->isSaleable()) : ?>
                                        
                                        <div class="control qty" data-mage-init='{
                                        "qtyInput":{"qtyInputSelector": "#qty-<?php /* @escapeNotVerified */ echo $_item->getId() ?>",
                                        "qtyIncrementSelector":"#inc-qty-<?php /* @escapeNotVerified */ echo $_item->getId() ?>",
                                        "qtyDecrementSelector":"#dec-qty-<?php /* @escapeNotVerified */ echo $_item->getId() ?>"
                                        }
                                    }'>     
                                            <div class="decreaseQty" id="dec-qty-<?php /* @escapeNotVerified */ echo $_item->getId() ?>" >-</div>
                                            <input type="number"
                                                   name="super_group[<?= /* @escapeNotVerified */ $_item->getId() ?>]"
                                                   data-selector="super_group[<?= /* @escapeNotVerified */ $_item->getId() ?>]"
                                                   value="<?= /* @escapeNotVerified */ $_item->getQty() * 1 ?>"
                                                   title="<?= /* @escapeNotVerified */ __('Qty') ?>"
                                                   class="input-text qty"
                                                   id="qty-<?php /* @escapeNotVerified */ echo $_item->getId() ?>"
                                                   data-validate="{'validate-grouped-qty':'#super-product-table-<?php echo $_product->getSku(); ?>'}"
                                                   data-default-qty="<?= /* @escapeNotVerified */ $_item->getQty() * 1 ?>"
                                                   data-errors-message-box="#validation-message-box-<?php echo $_product->getSku(); ?>"/>                                            
                                            <div class="increaseQty" id="inc-qty-<?php /* @escapeNotVerified */ echo $_item->getId() ?>">+</div>
                                        </div>
                                    <?php else: ?>
                                        <div class="stock" title="<?= /* @escapeNotVerified */ __('Availability') ?>">
                                            <span class="unavailable"><?= /* @escapeNotVerified */ __('Out of stock') ?></span>
                                        </div>
                                    <?php endif; ?>
                                    </td>
                                    <?php // endif; ?>
                                </tr>
                                <?php if ($block->getCanShowProductPrice($_product)
                                    && $block->getCanShowProductPrice($_item)
                                    && trim($block->getProductPriceHtml(
                                        $_item,
                                        \Magento\Catalog\Pricing\Price\TierPrice::PRICE_CODE
                                    ))): ?>
                                    <tr class="row-tier-price">
                                        <td colspan="2">
                                            <?= $block->getProductPriceHtml(
                                                $_item,
                                                \Magento\Catalog\Pricing\Price\TierPrice::PRICE_CODE
                                            ) ?>
                                        </td>
                                    </tr>
                                <?php endif; ?>
                            </tbody>
                            <?php  } ?>
                        <?php  } ?>
                    </table>
                </div>
                <?php  
                        // calculate maxprice and min price for group products
                        arsort($priceRange);
                        $maxprice = reset($priceRange);
                        $minprice = end($priceRange);
                        $currencyHelper = $this->helper('Magento\Framework\Pricing\Helper\Data');
                     ?>
                    <?php if($maxprice != $minprice){  ?>
                        <div id="group_product_price_<?php echo $_product->getId();  ?>" style="display:none;"><div id="product-price-<?php echo $_product->getId();?>" class="group-prod-price"><?php echo $currencyHelper->currency($minprice,true,false); ?> - <?php echo $currencyHelper->currency($maxprice,true,false);?></div></div>
                    <?php }else{ ?>
                        <div id="group_product_price_<?php echo $_product->getId();  ?>" style="display:none;"><div id="product-price-<?php echo $_product->getId();?>" class="group-prod-price"><?php echo $currencyHelper->currency($minprice,true,false); ?> </div></div>
                    <?php  } ?>
                        <script type="text/javascript">
                            require(["jquery","domReady!"], function ($) {
                             var productId = "<?php echo $_product->getId();  ?>";
                            $(".price-box[data-product-id='"+productId+"'] .price-box").html(jQuery("#group_product_price_"+productId).html());
                            });
                        </script>
                        <?php if ($_product->isSaleable()){ ?>
                        <div class="validation-box" id="validation-message-box-<?php echo $_product->getSku(); ?>"></div>
                        <div class="actions">
                            <button type="submit"
                                    title="<?=   __('Add to Cart'); ?>"
                                    class="action primary tocart"
                                    id="product-addtocart-button-<?php echo $_product->getSku() ?>">
                                <span><?= /* @escapeNotVerified */  __('Add to Cart'); ?></span>
                            </button>
                            <?= $block->getChildHtml('', true) ?>
                        </div>
                        <div class="mg-ajaxcart-dialog" id="ajaxcart-dialog-<?php echo $_product->getId() ?>">
						<div class="main-panel">
								<div class="product-info">
										<span class="msg">


											<?php echo __('Added to your basket');?>

											<a href="<?php echo $block->getUrl('checkout/cart'); ?>" class="button goto-cart cart-button"><i class="fas fa-shopping-basket"></i> <?php echo __('View basket');?></a> 

											<br>

											<div class="name"></div>

									</span>
								</div>
								<div style="clear:both;"></div>
						</div>
					</div>
                        <?php  } ?>
            <?php  // end grouped product code 
						 
						 
						 
                }elseif ($_product->getTypeId() == 'simple') {  //start simple product code  ?>
				
				<div class="simple-cart">
					
                                    <?php if ($_product->isSaleable()){ ?>
					
					
					
					<div class="add-cart-box">
					
						<div class="box-tocart">
							<div class="fieldset">
								<div class="field qty">
									<label class="label" for="qty"><span><?= /* @escapeNotVerified */ __('Qty') ?></span></label>
									<div class="control" data-mage-init='{
												"qtyInput":{"qtyInputSelector": "#qty-<?php /* @escapeNotVerified */ echo $_product->getId() ?>",
												"qtyIncrementSelector":"#inc-qty-<?php /* @escapeNotVerified */ echo $_product->getId() ?>",
												"qtyDecrementSelector":"#dec-qty-<?php /* @escapeNotVerified */ echo $_product->getId() ?>"
												}
											}'>
										<div class="decreaseQty" id="dec-qty-<?php /* @escapeNotVerified */ echo $_product->getId() ?>" >-</div>
										<input type="number"
											   name="qty"                                       
											   value="<?= /* @escapeNotVerified */ $block->getProductDefaultQty($_product) * 1 ?>"
											   title="<?= /* @escapeNotVerified */ __('Qty') ?>"
											   class="input-text qty"
											   id="qty-<?php /* @escapeNotVerified */ echo $_product->getId() ?>"
                                                                                           data-default-qty="<?= /* @escapeNotVerified */ $block->getProductDefaultQty($_product) * 1 ?>"
											   data-validate="<?= $block->escapeHtml(json_encode($block->getQuantityValidators())) ?>"
											   />
										<div class="increaseQty" id="inc-qty-<?php /* @escapeNotVerified */ echo $_product->getId() ?>">+</div>   
									</div>
								</div>
							</div>
						</div>

						<div class="actions">
							<button type="submit"
									title="<?= /* @escapeNotVerified */ __('Add to Cart'); ?>"
									class="action primary tocart"
									id="product-addtocart-button-<?php echo $_product->getSku() ?>">
								<span><?= /* @escapeNotVerified */ __('Add to Cart'); ?></span>
							</button>
							<?= $block->getChildHtml('', true) ?>
						</div>
                                            
                                            <div class="mg-ajaxcart-dialog" id="ajaxcart-dialog-<?php echo $_product->getId() ?>">
												<div class="main-panel">
														<div class="product-info">
																<span class="msg">


																	<?php echo __('Added to your basket');?>

																	<a href="<?php echo $block->getUrl('checkout/cart'); ?>" class="button goto-cart cart-button"><i class="fas fa-shopping-basket"></i> <?php echo __('View basket');?></a> 

																	<br>

																	<div class="name"></div>

															</span>
														</div>
														<div style="clear:both;"></div>
												</div>
											</div>
					
					</div>
					
					<?php }else{ ?>    
					<div class="out-stock">
						<div class="product-info-stock-sku">
							<div class="stock" title="Availability">
									<span class="stock-label">Availability: </span>
									<span class="unavailable"><?php echo __('Out of stock'); ?></span>
							</div>                                           
						</div>
					</div>

					<?php } ?>
					
					
				</div>
                
            <?php // end simple  product type  
				
				
				
            }elseif($_product->getTypeId() == 'configurable') {  // start configurable product type  
                    
                    $_attributes = $block->decorateArray($block->getAllowAttributes($_product));                    
                    ?>
                    <?php if ($_product->isSaleable() && count($_attributes)){?>
                         <?php foreach ($_attributes as $_attribute): ?>
					
                                <div class="field configurable required configurable-container-<?php echo $_product->getId() ?>">
                                    <label class="label" for="attribute<?= /* @escapeNotVerified */ $_attribute->getAttributeId() ?>">
                                        <span><?= $block->escapeHtml($_attribute->getProductAttribute()->getStoreLabel()) ?></span>
                                    </label>
                                    <div class="control config-select">
                                        <select name="super_attribute[<?= /* @escapeNotVerified */ $_attribute->getAttributeId() ?>]"
                                                data-selector="super_attribute[<?= /* @escapeNotVerified */ $_attribute->getAttributeId() ?>]"
                                                data-validate="{required:true}"
                                                id="attribute<?php /* @escapeNotVerified */ echo $_attribute->getAttributeId() ?>"
                                                class="super-attribute-select-completelook">
                                            <option value=""><?= /* @escapeNotVerified */ __('Choose an Option...') ?></option>
                                        </select>
                                    </div>
                                </div>                                
                            <?php endforeach; ?>
                            <script>
                                require([
                                    'jquery',
                                    'jquery/ui',
                                    'custompriceBox',
                                    'mdConfigurable'


                                ], function($){
                                    var priceBoxes = $('[data-role=priceBox]');

                                    priceBoxes = priceBoxes.filter(function(index, elem){
                                        return !$(elem).find('.price-from').length;
                                    });

                                    priceBoxes.custompriceBox({'priceConfig': <?php /* @escapeNotVerified */ echo $block->getPriceJsonConfig($_product) ?>});
                                });
                            </script>                          
                            
                                <script>
                        require(["jquery", "jquery/ui", "custompriceBox","mdConfigurable"], function ($) {
                            $('#product_addtocart_form_<?= $block->escapeHtml($_product->getSku()) ?>').configurable({
                                spConfig: <?php /* @escapeNotVerified */ echo $block->getJsonConfigCompletelook($_product) ?>,
                                priceHolderSelector: '.selection-product-price-<?php echo $_product->getId() ?> .price-box'
                            });
                        });
                    </script>
                    
                <?php }
                
                        if ($_product->isSaleable()){ ?>
					
						<div class="config-cart">
							<div class="box-tocart">
								<div class="fieldset">
									<?php if ($block->shouldRenderQuantity($_product)): ?>
									<div class="field qty">
										<label class="label" for="qty"><span><?= /* @escapeNotVerified */ __('Qty') ?></span></label>
										<div class="control" data-mage-init='{
																	"qtyInput":{"qtyInputSelector": "#qty-<?php /* @escapeNotVerified */ echo $_product->getId() ?>",
																	"qtyIncrementSelector":"#inc-qty-<?php /* @escapeNotVerified */ echo $_product->getId() ?>",
																	"qtyDecrementSelector":"#dec-qty-<?php /* @escapeNotVerified */ echo $_product->getId() ?>"
																	}
																}'>
											<div class="decreaseQty" id="dec-qty-<?php /* @escapeNotVerified */ echo $_product->getId() ?>" >-</div>
											<input type="number"
												   name="qty"
												   id="qty-<?php /* @escapeNotVerified */ echo $_product->getId() ?>"
												   value="<?= /* @escapeNotVerified */ $block->getProductDefaultQty($_product) * 1 ?>"
												   title="<?= /* @escapeNotVerified */ __('Qty') ?>"
												   class="input-text qty"
                                                                                                   data-default-qty="<?= /* @escapeNotVerified */ $block->getProductDefaultQty($_product) * 1 ?>"
												   data-validate="<?= $block->escapeHtml(json_encode($block->getQuantityValidators())) ?>"
												   />
											<div class="increaseQty" id="inc-qty-<?php /* @escapeNotVerified */ echo $_product->getId() ?>">+</div>
										</div>
									</div>
									<?php endif; ?>
									<div class="actions">
										<button type="submit"
												title="<?= /* @escapeNotVerified */ $buttonTitle ?>"
												class="action primary tocart"
												id="product-addtocart-button">
											<span><?= /* @escapeNotVerified */ $buttonTitle ?></span>
										</button>
										<?= $block->getChildHtml('', true) ?>
									</div>
								</div>
										<div class="mg-ajaxcart-dialog" id="ajaxcart-dialog-<?php echo $_product->getId() ?>">
											
											<div class="main-panel">
												<div class="product-info">
														<span class="msg">


															<?php echo __('Added to your basket');?>

															<a href="<?php echo $block->getUrl('checkout/cart'); ?>" class="button goto-cart cart-button"><i class="fas fa-shopping-basket"></i> <?php echo __('View basket');?></a> 

															<br>

															<div class="name"></div>

													</span>
												</div>
												<div style="clear:both;"></div>
										</div>
											
										
											
										</div>
							</div>
						</div>
                    <?php }else{ ?>
                            <div class="product-info-stock-sku">
                                <div class="stock" title="Availability">
                                        <span class="stock-label">Availability: </span>
                                        <span class="unavailable"><?php echo __('Out of stock'); ?></span>
                                </div>                                           
                            </div>
                    <?php } ?>   
                
                <?php  }  ?>
            
            
                    <script type="text/x-magento-init">
                    {
                        "#product_addtocart_form_<?php echo $_product->getSku() ?>": {
                            "Magento_Catalog/js/validate-product": {}
                        }
                    }
                </script>
                </form>
            <script>
				var x = window.matchMedia("(max-width: 479px)")
				
				var y = window.matchMedia("(max-width: 767px)")
				
				
				
				function openDescription(element) {
					
					jQuery(".sidenav").each(function( index ) {  
						jQuery(this).width(0);
					});
					
					 if (x.matches) { // If media query matches to 479
						document.getElementById(element).style.width = "350px";
					} 
					else if (y.matches) { // If media query matches t0 767
						document.getElementById(element).style.width = "500px";
					}
					else {
						document.getElementById(element).style.width = "650px";
					}
				}

				function closeDescription(element) {
							//console.log(element);
					document.getElementById(element).style.width = "0";
				}
				
			</script>
            
        <?php } ?>
                </div>
        </div>


    <?php }  
    
?>


