<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php /** @var $block \Magento\Checkout\Block\Onepage\Success */ ?>
<div class="checkout-success">
    <?php if ($block->getOrderId()):?>
        <?php if ($block->getCanViewOrder()) :?>
            <p><?= __('Your order number is: %1.', sprintf('<a href="%s" class="order-number"><strong>%s</strong></a>', $block->escapeHtml($block->getViewOrderUrl()), $block->escapeHtml($block->getOrderId()))) ?></p>
        <?php  else :?>
            <p><?= __('Your order # is: <span>%1</span>.', $block->escapeHtml($block->getOrderId())) ?></p>
        <?php endif;?>
            <p><?= /* @escapeNotVerified */ __('We\'ll email you an order confirmation with details and tracking info.') ?></p>
    <?php endif;?>

    <?= $block->getAdditionalInfoHtml() ?>

    <div class="actions-toolbar">
        <div class="primary">
            <a class="action primary continue" href="<?= /* @escapeNotVerified */ $block->getContinueUrl() ?>"><span><?= /* @escapeNotVerified */ __('Continue Shopping') ?></span></a>
        </div>
    </div>

       <?php $helper = $this->helper('Homescapes\General\Helper\Data');  
         if ($block->getOrderId()){
            
            $order = $helper->loadOrderByIncrementById($block->getOrderId());

            $quoteId = $order->getQuoteId();
            $quote = $helper->loadQuoteById($quoteId);
            $method = $quote->getCheckoutMethod();        

            if ($method == 'login_in'){ 
                 $CommissionGroupCode = 'Existing'; 
            } elseif($method == 'guest') { 
                 $CommissionGroupCode = 'New'; 
            }
            
            $subtotal = $order->getSubtotal();
            $gtotal = $order->getGrandTotal();   
             

            $total = $order->getGrandTotal();
            $totalwithoutshipping = $order->getGrandTotal() - $order->getShippingAmount();
            $totalwithoutshipping = $totalwithoutshipping / 1.2; 

            $orderDetails = $order->getData();
            $couponCode = $orderDetails['coupon_code'];
            if($couponCode){
              $coupon = $couponCode;
              $CommissionGroupCode = 'Voucher'; //Andy added to give 'Voucher' as a comission group if voucher is used.
            }else{
              $coupon = ' ';
            } 

            $subtotal = $order->getSubtotal();
            $gtotal = $order->getGrandTotal();

            ?>

            <!-- Google Code for Conversion Conversion Page -->

            <script type="text/javascript">

            /* <![CDATA[ */

            var google_conversion_id = 983804255;

            var google_conversion_language = "en";

            var google_conversion_format = "2";

            var google_conversion_color = "ffffff";

            var google_conversion_label = "pMncCLq6uWUQ39KO1QM";

            var google_conversion_value = <?php echo $gtotal;?>;

            var google_conversion_currency = "<?php echo $helper->currentCurrencyCode(); ?>";

            var google_remarketing_only = false;

            /* ]]> */

            </script>

            <script type="text/javascript" src="//www.googleadservices.com/pagead/conversion.js">

            </script>

            <noscript>

            <div style="display:inline;">
            <img height="1" width="1" style="border-style:none;" alt="" src="//www.googleadservices.com/pagead/conversion/983804255/?value=1.00&amp;currency_code=<?php echo $helper->currentCurrencyCode(); ?>&amp;label=pMncCLq6uWUQ39KO1QM&amp;guid=ON&amp;script=0"/>
            </div>

            </noscript>

            <?php /************ AWIN Image pixel code ************/ ?>
            <img border="0" height="0" src="https://www.awin1.com/sread.img?tt=ns&tv=2&merchant=6284&amount=<?php echo round($totalwithoutshipping, 2); ?>&ch=aw&cr=<?php echo $helper->currentCurrencyCode(); ?>&parts=<?php echo $CommissionGroupCode; ?>:<?php echo round($totalwithoutshipping, 2); ?>&ref=<?php echo $this->getOrderId(); ?>&testmode=0&vc=<?php echo $coupon; ?>" style="display: none;" width="0">

            <?php /************ Javascript code ************/ ?>

            <script type="text/javascript">
            //<![CDATA[
            /*** Do not change ***/
            var AWIN = {};
            AWIN.Tracking = {};
            AWIN.Tracking.Sale = {};
            /*** Set your transaction parameters ***/
            AWIN.Tracking.Sale.amount = "<?php echo round($totalwithoutshipping, 2); ?>";
            AWIN.Tracking.Sale.channel = "aw"; 
            AWIN.Tracking.Sale.currency = "<?php echo $helper->currentCurrencyCode(); ?>";
            AWIN.Tracking.Sale.orderRef = "<?php echo $this->getOrderId(); ?>";
            AWIN.Tracking.Sale.parts = "<?php echo $CommissionGroupCode; ?>:<?php echo round($totalwithoutshipping, 2); ?>";
            AWIN.Tracking.Sale.test = "0";
            AWIN.Tracking.Sale.voucher = "<?php echo $coupon; ?>";
            //]]>
            </script>

            <?php /**********Affiliate window code**********/?>
            <form style="display: none;" name="aw_basket_form">
            <textarea wrap="physical" id="aw_basket">
              <?php foreach($order->getAllItems() as $items) {
                $productidd = $helper->loadProduct($items->getProductId());                
                //$cats = $productidd->getCategoryId();
                $cats = $productidd->getCategoryIds();
                
                $firstCategoryId = $cats[0];
                
                $category = $helper->loadCategory($firstCategoryId);
                $categoryName = $category->getName();                
                ?>
                <?php //Andy 23-03-2015 product without VAT We need each product without VAT.
                //Something like.
                $ProductPriceWithoutVat = $items->getPrice();
                $ProductPriceWithoutVat = $ProductPriceWithoutVat / 1.2;
                //Then replace echo $items->getPrice(); below with $ProductPriceWithoutVat
                ?>
                AW:P|6284|<?php echo $this->getOrderId(); ?>|<?php echo $items->getId(); ?>|<?php echo $items->getName(); ?>|<?php echo $ProductPriceWithoutVat; ?>|<?php echo $items->getQtyToShip(); ?>|<?php echo $items->getSku(); ?>|<?php echo $CommissionGroupCode; ?>|<?php echo $categoryName; ?><?php echo "\r\n";?>
              <?php } ?>
              </textarea>
            </form> 
            <script defer="defer" src="https://www.dwin1.com/6284.js" type="text/javascript"></script>

            
           <?php 
            $currency = $helper->currentCurrencyCode();
            $date = date("d-m-Y");// current date
            $shipdate = strtotime(date("Y-m-d", strtotime($date)) . " +1 day");
            $deldate = strtotime(date("Y-m-d", strtotime($date)) . " +3 day");
            $discountTotal = 0;
            
            /*echo "<pre>";
            print_r($currency);
            die('sdfljsdl');*/
            foreach ($order->getAllItems() as $items1){
                $discountTotal += $items1->getDiscountAmount();
            }
            ?> 

            <!-- START Google Certified Shops Order -->
            <div id="gts-order" style="display:none;" translate="no">

              <!-- start order and merchant information -->
              <span id="gts-o-id"><?php echo $this->getOrderId(); ?></span>
              <span id="gts-o-domain"><?php echo "www.homescapesonline.com"; ?></span>
              <span id="gts-o-email"><?php echo $order->getCustomerEmail(); ?></span>
              <span id="gts-o-country">GB</span>
              <span id="gts-o-currency"><?php echo $currency; ?></span>
              <span id="gts-o-total"><?php echo round($totalwithoutshipping, 2); ?></span>
              <span id="gts-o-discounts"><?php echo $discountTotal; ?></span>
              <span id="gts-o-shipping-total"><?php echo round($order->getShippingAmount(),2); ?></span>
              <span id="gts-o-tax-total"><?php echo round($order->getTaxAmount(),2); ?></span>
              <span id="gts-o-est-ship-date"><?php echo date("Y-m-d",$shipdate); ?></span>
              <span id="gts-o-est-delivery-date"><?php echo date("Y-m-d",$deldate); ?></span>
              <span id="gts-o-has-preorder">N</span>
              <span id="gts-o-has-digital">N</span>
            <!-- end order and merchant information -->
            <!-- start repeated item specific information -->
              <!-- item example: this area repeated for each item in the order -->
            <?php foreach($order->getAllItems() as $items) {
                $productidd = $helper->loadProduct($items->getProductId());                
                //$cats = $productidd->getCategoryId();
                $cats = $productidd->getCategoryIds();
                
                $firstCategoryId = $cats[0];
                
                $category = $helper->loadCategory($firstCategoryId);
                $categoryName = $category->getName();                
               ?>
               <?php
                $ProductPriceWithoutVat = $items->getPrice();
                $ProductPriceWithoutVat = $ProductPriceWithoutVat / 1.2;
                ?>
              <span class="gts-item">
                <span class="gts-i-name"><?php echo $items->getName(); ?></span>
                <span class="gts-i-price"><?php echo round($items->getPrice(),2); ?></span>
                <span class="gts-i-quantity"><?php echo $items->getQtyToShip(); ?></span>
                <span class="gts-i-prodsearch-id"><?php echo $items->getSku(); ?></span>
                <span class="gts-i-prodsearch-store-id">100627206</span>
                <span class="gts-i-prodsearch-country">UK</span>
                <span class="gts-i-prodsearch-language">en</span>
              </span>
              <!-- end item 1 example -->
              <!-- end repeated item specific information -->
            <?php } ?>
            </div>
            <!-- END Google Certified Shops Order -->    


            <!-- Facebook Pixel Code -->
            <script type="text/javascript"> 
              !function(f,b,e,v,n,t,s){if(f.fbq)return;n=f.fbq=function(){n.callMethod?
              n.callMethod.apply(n,arguments):n.queue.push(arguments)};if(!f._fbq)f._fbq=n;
              n.push=n;n.loaded=!0;n.version='2.0';n.queue=[];t=b.createElement(e);t.async=!0;
              t.src=v;s=b.getElementsByTagName(e)[0];s.parentNode.insertBefore(t,s)}(window,
              document,'script','https://connect.facebook.net/en_US/fbevents.js');

              fbq('init', '225375511131707');
              fbq('track', "PageView");
            </script>

            <noscript>
              <img height="1" width="1" style="display:none"
              src="https://www.facebook.com/tr?id=225375511131707&ev=PageView&noscript=1"
              />
            </noscript>

            <script type="text/javascript"> 
              fbq('track', 'Purchase', {value: '<?php echo $order->getGrandTotal(); ?>', currency:'GBP'});
            </script>
            <!-- End Facebook Pixel Code -->

            <!-- Bing Tracking Code -->
            <!-- Additional code (main code) is already updated in head section -->
            <script type="text/javascript"> 
              window.uetq = window.uetq || [];
              window.uetq.push({ 'gv': <?php echo $order->getGrandTotal(); ?> });
            </script>
            <!-- End Bing Tracking Code -->

            <?php
            $subtotal = $order->getSubtotal();
            $order_id = $order->getId(); //the id of the order
            //$order->getIncrementId();//the increment id of the order
            $gtotal = $order->getGrandTotal();//grand total of the order 
            $address = $order->getBillingAddress()->getData();
            $city = $address['city'];
            $state = $address['region'];
            $country = $address['country_id'];
            $shippingVal=$order->getShippingAmount();
            $taxAmount=$order->getTaxAmount();
            ?>
            <script>
            dataLayer.push({
                'event' :'order_success',
                'transactionId': '<?php echo $order_id; ?>',
                'transactionAffiliation': '',
                'transactionTotal': <?php echo $gtotal; ?>,
                'transactionTax': <?php echo $taxAmount; ?>,
                'transactionShipping': <?php echo $shippingVal; ?>,
                'transactionProducts': [
              <?php 
                $i=0;
                $items = $order->getAllItems();
                $itemcount=count($items);
                $name=array();
                $unitPrice=array();
                $sku=array();
                $ids=array();
                $qty=array();
                foreach ($items as $itemId => $item)
                {
                    $i++;
                    if($i > 1)
                    {
                    echo ",";
                    }
                ?>
              {
                    'sku': '<?php echo $item->getSku(); ?>',
                    'name': "<?php echo $item->getName(); ?>",
                    'category': '',
                    'price': <?php echo $item->getPrice(); ?>,
                    'quantity': <?php echo $item->getQtyOrdered(); ?>
                }
              <?php 
            }
            ?>
              
              ]
            });
            </script>  






          <?php }?>

</div>
